// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/data/video/VideoSourceStream.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout.data.video;

/**
 * Protobuf type {@code com.ifit.glassos.VideoSourceStream}
 */
public  final class VideoSourceStream extends
    com.google.protobuf.GeneratedMessageLite<
        VideoSourceStream, VideoSourceStream.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.VideoSourceStream)
    VideoSourceStreamOrBuilder {
  private VideoSourceStream() {
    codec_ = "";
    container_ = "";
    src_ = "";
  }
  public static final int CODEC_FIELD_NUMBER = 1;
  private java.lang.String codec_;
  /**
   * <code>string codec = 1;</code>
   * @return The codec.
   */
  @java.lang.Override
  public java.lang.String getCodec() {
    return codec_;
  }
  /**
   * <code>string codec = 1;</code>
   * @return The bytes for codec.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodecBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(codec_);
  }
  /**
   * <code>string codec = 1;</code>
   * @param value The codec to set.
   */
  private void setCodec(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    codec_ = value;
  }
  /**
   * <code>string codec = 1;</code>
   */
  private void clearCodec() {

    codec_ = getDefaultInstance().getCodec();
  }
  /**
   * <code>string codec = 1;</code>
   * @param value The bytes for codec to set.
   */
  private void setCodecBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    codec_ = value.toStringUtf8();

  }

  public static final int CONTAINER_FIELD_NUMBER = 2;
  private java.lang.String container_;
  /**
   * <code>string container = 2;</code>
   * @return The container.
   */
  @java.lang.Override
  public java.lang.String getContainer() {
    return container_;
  }
  /**
   * <code>string container = 2;</code>
   * @return The bytes for container.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContainerBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(container_);
  }
  /**
   * <code>string container = 2;</code>
   * @param value The container to set.
   */
  private void setContainer(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    container_ = value;
  }
  /**
   * <code>string container = 2;</code>
   */
  private void clearContainer() {

    container_ = getDefaultInstance().getContainer();
  }
  /**
   * <code>string container = 2;</code>
   * @param value The bytes for container to set.
   */
  private void setContainerBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    container_ = value.toStringUtf8();

  }

  public static final int SRC_FIELD_NUMBER = 3;
  private java.lang.String src_;
  /**
   * <code>string src = 3;</code>
   * @return The src.
   */
  @java.lang.Override
  public java.lang.String getSrc() {
    return src_;
  }
  /**
   * <code>string src = 3;</code>
   * @return The bytes for src.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSrcBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(src_);
  }
  /**
   * <code>string src = 3;</code>
   * @param value The src to set.
   */
  private void setSrc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    src_ = value;
  }
  /**
   * <code>string src = 3;</code>
   */
  private void clearSrc() {

    src_ = getDefaultInstance().getSrc();
  }
  /**
   * <code>string src = 3;</code>
   * @param value The bytes for src to set.
   */
  private void setSrcBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    src_ = value.toStringUtf8();

  }

  public static final int BITRATE_FIELD_NUMBER = 4;
  private int bitrate_;
  /**
   * <code>int32 bitrate = 4;</code>
   * @return The bitrate.
   */
  @java.lang.Override
  public int getBitrate() {
    return bitrate_;
  }
  /**
   * <code>int32 bitrate = 4;</code>
   * @param value The bitrate to set.
   */
  private void setBitrate(int value) {
    
    bitrate_ = value;
  }
  /**
   * <code>int32 bitrate = 4;</code>
   */
  private void clearBitrate() {

    bitrate_ = 0;
  }

  public static final int WIDTH_FIELD_NUMBER = 5;
  private int width_;
  /**
   * <code>int32 width = 5;</code>
   * @return The width.
   */
  @java.lang.Override
  public int getWidth() {
    return width_;
  }
  /**
   * <code>int32 width = 5;</code>
   * @param value The width to set.
   */
  private void setWidth(int value) {
    
    width_ = value;
  }
  /**
   * <code>int32 width = 5;</code>
   */
  private void clearWidth() {

    width_ = 0;
  }

  public static final int HEIGHT_FIELD_NUMBER = 6;
  private int height_;
  /**
   * <code>int32 height = 6;</code>
   * @return The height.
   */
  @java.lang.Override
  public int getHeight() {
    return height_;
  }
  /**
   * <code>int32 height = 6;</code>
   * @param value The height to set.
   */
  private void setHeight(int value) {
    
    height_ = value;
  }
  /**
   * <code>int32 height = 6;</code>
   */
  private void clearHeight() {

    height_ = 0;
  }

  public static final int SIZE_FIELD_NUMBER = 7;
  private double size_;
  /**
   * <code>double size = 7;</code>
   * @return The size.
   */
  @java.lang.Override
  public double getSize() {
    return size_;
  }
  /**
   * <code>double size = 7;</code>
   * @param value The size to set.
   */
  private void setSize(double value) {
    
    size_ = value;
  }
  /**
   * <code>double size = 7;</code>
   */
  private void clearSize() {

    size_ = 0D;
  }

  public static final int DURATION_FIELD_NUMBER = 8;
  private int duration_;
  /**
   * <code>int32 duration = 8;</code>
   * @return The duration.
   */
  @java.lang.Override
  public int getDuration() {
    return duration_;
  }
  /**
   * <code>int32 duration = 8;</code>
   * @param value The duration to set.
   */
  private void setDuration(int value) {
    
    duration_ = value;
  }
  /**
   * <code>int32 duration = 8;</code>
   */
  private void clearDuration() {

    duration_ = 0;
  }

  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.workout.data.video.VideoSourceStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.workout.data.video.VideoSourceStream prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.VideoSourceStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.workout.data.video.VideoSourceStream, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.VideoSourceStream)
      com.ifit.glassos.workout.data.video.VideoSourceStreamOrBuilder {
    // Construct using com.ifit.glassos.workout.data.video.VideoSourceStream.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string codec = 1;</code>
     * @return The codec.
     */
    @java.lang.Override
    public java.lang.String getCodec() {
      return instance.getCodec();
    }
    /**
     * <code>string codec = 1;</code>
     * @return The bytes for codec.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodecBytes() {
      return instance.getCodecBytes();
    }
    /**
     * <code>string codec = 1;</code>
     * @param value The codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodec(
        java.lang.String value) {
      copyOnWrite();
      instance.setCodec(value);
      return this;
    }
    /**
     * <code>string codec = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodec() {
      copyOnWrite();
      instance.clearCodec();
      return this;
    }
    /**
     * <code>string codec = 1;</code>
     * @param value The bytes for codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodecBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCodecBytes(value);
      return this;
    }

    /**
     * <code>string container = 2;</code>
     * @return The container.
     */
    @java.lang.Override
    public java.lang.String getContainer() {
      return instance.getContainer();
    }
    /**
     * <code>string container = 2;</code>
     * @return The bytes for container.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContainerBytes() {
      return instance.getContainerBytes();
    }
    /**
     * <code>string container = 2;</code>
     * @param value The container to set.
     * @return This builder for chaining.
     */
    public Builder setContainer(
        java.lang.String value) {
      copyOnWrite();
      instance.setContainer(value);
      return this;
    }
    /**
     * <code>string container = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContainer() {
      copyOnWrite();
      instance.clearContainer();
      return this;
    }
    /**
     * <code>string container = 2;</code>
     * @param value The bytes for container to set.
     * @return This builder for chaining.
     */
    public Builder setContainerBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContainerBytes(value);
      return this;
    }

    /**
     * <code>string src = 3;</code>
     * @return The src.
     */
    @java.lang.Override
    public java.lang.String getSrc() {
      return instance.getSrc();
    }
    /**
     * <code>string src = 3;</code>
     * @return The bytes for src.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSrcBytes() {
      return instance.getSrcBytes();
    }
    /**
     * <code>string src = 3;</code>
     * @param value The src to set.
     * @return This builder for chaining.
     */
    public Builder setSrc(
        java.lang.String value) {
      copyOnWrite();
      instance.setSrc(value);
      return this;
    }
    /**
     * <code>string src = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrc() {
      copyOnWrite();
      instance.clearSrc();
      return this;
    }
    /**
     * <code>string src = 3;</code>
     * @param value The bytes for src to set.
     * @return This builder for chaining.
     */
    public Builder setSrcBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSrcBytes(value);
      return this;
    }

    /**
     * <code>int32 bitrate = 4;</code>
     * @return The bitrate.
     */
    @java.lang.Override
    public int getBitrate() {
      return instance.getBitrate();
    }
    /**
     * <code>int32 bitrate = 4;</code>
     * @param value The bitrate to set.
     * @return This builder for chaining.
     */
    public Builder setBitrate(int value) {
      copyOnWrite();
      instance.setBitrate(value);
      return this;
    }
    /**
     * <code>int32 bitrate = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBitrate() {
      copyOnWrite();
      instance.clearBitrate();
      return this;
    }

    /**
     * <code>int32 width = 5;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return instance.getWidth();
    }
    /**
     * <code>int32 width = 5;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(int value) {
      copyOnWrite();
      instance.setWidth(value);
      return this;
    }
    /**
     * <code>int32 width = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      copyOnWrite();
      instance.clearWidth();
      return this;
    }

    /**
     * <code>int32 height = 6;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return instance.getHeight();
    }
    /**
     * <code>int32 height = 6;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(int value) {
      copyOnWrite();
      instance.setHeight(value);
      return this;
    }
    /**
     * <code>int32 height = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      copyOnWrite();
      instance.clearHeight();
      return this;
    }

    /**
     * <code>double size = 7;</code>
     * @return The size.
     */
    @java.lang.Override
    public double getSize() {
      return instance.getSize();
    }
    /**
     * <code>double size = 7;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(double value) {
      copyOnWrite();
      instance.setSize(value);
      return this;
    }
    /**
     * <code>double size = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      copyOnWrite();
      instance.clearSize();
      return this;
    }

    /**
     * <code>int32 duration = 8;</code>
     * @return The duration.
     */
    @java.lang.Override
    public int getDuration() {
      return instance.getDuration();
    }
    /**
     * <code>int32 duration = 8;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(int value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <code>int32 duration = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.VideoSourceStream)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.workout.data.video.VideoSourceStream();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "codec_",
            "container_",
            "src_",
            "bitrate_",
            "width_",
            "height_",
            "size_",
            "duration_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0000\u0001\b\b\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0004\u0005\u0004\u0006\u0004\u0007\u0000\b\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.workout.data.video.VideoSourceStream> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.workout.data.video.VideoSourceStream.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.workout.data.video.VideoSourceStream>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.VideoSourceStream)
  private static final com.ifit.glassos.workout.data.video.VideoSourceStream DEFAULT_INSTANCE;
  static {
    VideoSourceStream defaultInstance = new VideoSourceStream();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      VideoSourceStream.class, defaultInstance);
  }

  public static com.ifit.glassos.workout.data.video.VideoSourceStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<VideoSourceStream> PARSER;

  public static com.google.protobuf.Parser<VideoSourceStream> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

