/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_WEATHER_ALERT_MESG_LISTENER_HPP)
#define FIT_WEATHER_ALERT_MESG_LISTENER_HPP

#include "fit_weather_alert_mesg.hpp"

namespace fit
{

class WeatherAlertMesgListener
{
public:
    virtual ~WeatherAlertMesgListener() {}
    virtual void OnMesg(WeatherAlertMesg& mesg) = 0;
};

} // namespace fit

#endif // !defined(FIT_WEATHER_ALERT_MESG_LISTENER_HPP)
