// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/data/Control.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout.data;

public interface ControlListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.ControlList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .com.ifit.glassos.Control controls = 1;</code>
   */
  java.util.List<com.ifit.glassos.workout.data.Control> 
      getControlsList();
  /**
   * <code>repeated .com.ifit.glassos.Control controls = 1;</code>
   */
  com.ifit.glassos.workout.data.Control getControls(int index);
  /**
   * <code>repeated .com.ifit.glassos.Control controls = 1;</code>
   */
  int getControlsCount();
}
