// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/data/ScaledControls.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout.data;

public interface ScaledControlsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.ScaledControls)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.ifit.glassos.ControlList minus6 = 1;</code>
   * @return Whether the minus6 field is set.
   */
  boolean hasMinus6();
  /**
   * <code>.com.ifit.glassos.ControlList minus6 = 1;</code>
   * @return The minus6.
   */
  com.ifit.glassos.workout.data.ControlList getMinus6();

  /**
   * <code>.com.ifit.glassos.ControlList minus5 = 2;</code>
   * @return Whether the minus5 field is set.
   */
  boolean hasMinus5();
  /**
   * <code>.com.ifit.glassos.ControlList minus5 = 2;</code>
   * @return The minus5.
   */
  com.ifit.glassos.workout.data.ControlList getMinus5();

  /**
   * <code>.com.ifit.glassos.ControlList minus4 = 3;</code>
   * @return Whether the minus4 field is set.
   */
  boolean hasMinus4();
  /**
   * <code>.com.ifit.glassos.ControlList minus4 = 3;</code>
   * @return The minus4.
   */
  com.ifit.glassos.workout.data.ControlList getMinus4();

  /**
   * <code>.com.ifit.glassos.ControlList minus3 = 4;</code>
   * @return Whether the minus3 field is set.
   */
  boolean hasMinus3();
  /**
   * <code>.com.ifit.glassos.ControlList minus3 = 4;</code>
   * @return The minus3.
   */
  com.ifit.glassos.workout.data.ControlList getMinus3();

  /**
   * <code>.com.ifit.glassos.ControlList minus2 = 5;</code>
   * @return Whether the minus2 field is set.
   */
  boolean hasMinus2();
  /**
   * <code>.com.ifit.glassos.ControlList minus2 = 5;</code>
   * @return The minus2.
   */
  com.ifit.glassos.workout.data.ControlList getMinus2();

  /**
   * <code>.com.ifit.glassos.ControlList minus1 = 6;</code>
   * @return Whether the minus1 field is set.
   */
  boolean hasMinus1();
  /**
   * <code>.com.ifit.glassos.ControlList minus1 = 6;</code>
   * @return The minus1.
   */
  com.ifit.glassos.workout.data.ControlList getMinus1();

  /**
   * <code>.com.ifit.glassos.ControlList plus1 = 7;</code>
   * @return Whether the plus1 field is set.
   */
  boolean hasPlus1();
  /**
   * <code>.com.ifit.glassos.ControlList plus1 = 7;</code>
   * @return The plus1.
   */
  com.ifit.glassos.workout.data.ControlList getPlus1();

  /**
   * <code>.com.ifit.glassos.ControlList plus2 = 8;</code>
   * @return Whether the plus2 field is set.
   */
  boolean hasPlus2();
  /**
   * <code>.com.ifit.glassos.ControlList plus2 = 8;</code>
   * @return The plus2.
   */
  com.ifit.glassos.workout.data.ControlList getPlus2();

  /**
   * <code>.com.ifit.glassos.ControlList plus3 = 9;</code>
   * @return Whether the plus3 field is set.
   */
  boolean hasPlus3();
  /**
   * <code>.com.ifit.glassos.ControlList plus3 = 9;</code>
   * @return The plus3.
   */
  com.ifit.glassos.workout.data.ControlList getPlus3();

  /**
   * <code>.com.ifit.glassos.ControlList plus4 = 10;</code>
   * @return Whether the plus4 field is set.
   */
  boolean hasPlus4();
  /**
   * <code>.com.ifit.glassos.ControlList plus4 = 10;</code>
   * @return The plus4.
   */
  com.ifit.glassos.workout.data.ControlList getPlus4();

  /**
   * <code>.com.ifit.glassos.ControlList plus5 = 11;</code>
   * @return Whether the plus5 field is set.
   */
  boolean hasPlus5();
  /**
   * <code>.com.ifit.glassos.ControlList plus5 = 11;</code>
   * @return The plus5.
   */
  com.ifit.glassos.workout.data.ControlList getPlus5();

  /**
   * <code>.com.ifit.glassos.ControlList plus6 = 12;</code>
   * @return Whether the plus6 field is set.
   */
  boolean hasPlus6();
  /**
   * <code>.com.ifit.glassos.ControlList plus6 = 12;</code>
   * @return The plus6.
   */
  com.ifit.glassos.workout.data.ControlList getPlus6();

  /**
   * <code>.com.ifit.glassos.ControlList plus7 = 13;</code>
   * @return Whether the plus7 field is set.
   */
  boolean hasPlus7();
  /**
   * <code>.com.ifit.glassos.ControlList plus7 = 13;</code>
   * @return The plus7.
   */
  com.ifit.glassos.workout.data.ControlList getPlus7();

  /**
   * <code>.com.ifit.glassos.ControlList plus8 = 14;</code>
   * @return Whether the plus8 field is set.
   */
  boolean hasPlus8();
  /**
   * <code>.com.ifit.glassos.ControlList plus8 = 14;</code>
   * @return The plus8.
   */
  com.ifit.glassos.workout.data.ControlList getPlus8();

  /**
   * <code>.com.ifit.glassos.ControlList plus9 = 15;</code>
   * @return Whether the plus9 field is set.
   */
  boolean hasPlus9();
  /**
   * <code>.com.ifit.glassos.ControlList plus9 = 15;</code>
   * @return The plus9.
   */
  com.ifit.glassos.workout.data.ControlList getPlus9();

  /**
   * <code>.com.ifit.glassos.ControlList plus10 = 16;</code>
   * @return Whether the plus10 field is set.
   */
  boolean hasPlus10();
  /**
   * <code>.com.ifit.glassos.ControlList plus10 = 16;</code>
   * @return The plus10.
   */
  com.ifit.glassos.workout.data.ControlList getPlus10();

  /**
   * <code>.com.ifit.glassos.ControlList plus11 = 17;</code>
   * @return Whether the plus11 field is set.
   */
  boolean hasPlus11();
  /**
   * <code>.com.ifit.glassos.ControlList plus11 = 17;</code>
   * @return The plus11.
   */
  com.ifit.glassos.workout.data.ControlList getPlus11();

  /**
   * <code>.com.ifit.glassos.ControlList plus12 = 18;</code>
   * @return Whether the plus12 field is set.
   */
  boolean hasPlus12();
  /**
   * <code>.com.ifit.glassos.ControlList plus12 = 18;</code>
   * @return The plus12.
   */
  com.ifit.glassos.workout.data.ControlList getPlus12();
}
