// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/data/WorkoutFilter.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout.data;

/**
 * Protobuf enum {@code com.ifit.glassos.WorkoutFilter}
 */
public enum WorkoutFilter
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>WORKOUT_FILTER_UNKNOWN = 0;</code>
   */
  WORKOUT_FILTER_UNKNOWN(0),
  /**
   * <code>WORKOUT_FILTER_IFIT_BUILT = 1;</code>
   */
  WORKOUT_FILTER_IFIT_BUILT(1),
  /**
   * <code>WORKOUT_FILTER_IS_MANUAL = 2;</code>
   */
  WORKOUT_FILTER_IS_MANUAL(2),
  /**
   * <code>WORKOUT_FILTER_IS_MAP = 3;</code>
   */
  WORKOUT_FILTER_IS_MAP(3),
  /**
   * <code>WORKOUT_FILTER_IS_VAULT = 4;</code>
   */
  WORKOUT_FILTER_IS_VAULT(4),
  /**
   * <code>WORKOUT_FILTER_IS_VIDEO = 5;</code>
   */
  WORKOUT_FILTER_IS_VIDEO(5),
  /**
   * <code>WORKOUT_FILTER_IS_VUE = 6;</code>
   */
  WORKOUT_FILTER_IS_VUE(6),
  /**
   * <code>WORKOUT_FILTER_PORTRAIT_ORIENTATION = 7;</code>
   */
  WORKOUT_FILTER_PORTRAIT_ORIENTATION(7),
  /**
   * <code>WORKOUT_FILTER_OFF_EQUIPMENT = 8;</code>
   */
  WORKOUT_FILTER_OFF_EQUIPMENT(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>WORKOUT_FILTER_UNKNOWN = 0;</code>
   */
  public static final int WORKOUT_FILTER_UNKNOWN_VALUE = 0;
  /**
   * <code>WORKOUT_FILTER_IFIT_BUILT = 1;</code>
   */
  public static final int WORKOUT_FILTER_IFIT_BUILT_VALUE = 1;
  /**
   * <code>WORKOUT_FILTER_IS_MANUAL = 2;</code>
   */
  public static final int WORKOUT_FILTER_IS_MANUAL_VALUE = 2;
  /**
   * <code>WORKOUT_FILTER_IS_MAP = 3;</code>
   */
  public static final int WORKOUT_FILTER_IS_MAP_VALUE = 3;
  /**
   * <code>WORKOUT_FILTER_IS_VAULT = 4;</code>
   */
  public static final int WORKOUT_FILTER_IS_VAULT_VALUE = 4;
  /**
   * <code>WORKOUT_FILTER_IS_VIDEO = 5;</code>
   */
  public static final int WORKOUT_FILTER_IS_VIDEO_VALUE = 5;
  /**
   * <code>WORKOUT_FILTER_IS_VUE = 6;</code>
   */
  public static final int WORKOUT_FILTER_IS_VUE_VALUE = 6;
  /**
   * <code>WORKOUT_FILTER_PORTRAIT_ORIENTATION = 7;</code>
   */
  public static final int WORKOUT_FILTER_PORTRAIT_ORIENTATION_VALUE = 7;
  /**
   * <code>WORKOUT_FILTER_OFF_EQUIPMENT = 8;</code>
   */
  public static final int WORKOUT_FILTER_OFF_EQUIPMENT_VALUE = 8;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WorkoutFilter valueOf(int value) {
    return forNumber(value);
  }

  public static WorkoutFilter forNumber(int value) {
    switch (value) {
      case 0: return WORKOUT_FILTER_UNKNOWN;
      case 1: return WORKOUT_FILTER_IFIT_BUILT;
      case 2: return WORKOUT_FILTER_IS_MANUAL;
      case 3: return WORKOUT_FILTER_IS_MAP;
      case 4: return WORKOUT_FILTER_IS_VAULT;
      case 5: return WORKOUT_FILTER_IS_VIDEO;
      case 6: return WORKOUT_FILTER_IS_VUE;
      case 7: return WORKOUT_FILTER_PORTRAIT_ORIENTATION;
      case 8: return WORKOUT_FILTER_OFF_EQUIPMENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WorkoutFilter>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WorkoutFilter> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WorkoutFilter>() {
          @java.lang.Override
          public WorkoutFilter findValueByNumber(int number) {
            return WorkoutFilter.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return WorkoutFilterVerifier.INSTANCE;
  }

  private static final class WorkoutFilterVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WorkoutFilterVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return WorkoutFilter.forNumber(number) != null;
          }
        };

  private final int value;

  private WorkoutFilter(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.ifit.glassos.WorkoutFilter)
}

