// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/data/WorkoutSessionItem.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout.data;

/**
 * Protobuf type {@code com.ifit.glassos.WorkoutSessionItemList}
 */
public  final class WorkoutSessionItemList extends
    com.google.protobuf.GeneratedMessageLite<
        WorkoutSessionItemList, WorkoutSessionItemList.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.WorkoutSessionItemList)
    WorkoutSessionItemListOrBuilder {
  private WorkoutSessionItemList() {
    items_ = emptyProtobufList();
  }
  public static final int ITEMS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.ifit.glassos.workout.data.WorkoutSessionItem> items_;
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ifit.glassos.workout.data.WorkoutSessionItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  public java.util.List<? extends com.ifit.glassos.workout.data.WorkoutSessionItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  @java.lang.Override
  public com.ifit.glassos.workout.data.WorkoutSessionItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  public com.ifit.glassos.workout.data.WorkoutSessionItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }
  private void ensureItemsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.ifit.glassos.workout.data.WorkoutSessionItem> tmp = items_;
    if (!tmp.isModifiable()) {
      items_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  private void setItems(
      int index, com.ifit.glassos.workout.data.WorkoutSessionItem value) {
    value.getClass();
  ensureItemsIsMutable();
    items_.set(index, value);
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  private void addItems(com.ifit.glassos.workout.data.WorkoutSessionItem value) {
    value.getClass();
  ensureItemsIsMutable();
    items_.add(value);
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  private void addItems(
      int index, com.ifit.glassos.workout.data.WorkoutSessionItem value) {
    value.getClass();
  ensureItemsIsMutable();
    items_.add(index, value);
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  private void addAllItems(
      java.lang.Iterable<? extends com.ifit.glassos.workout.data.WorkoutSessionItem> values) {
    ensureItemsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, items_);
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  private void clearItems() {
    items_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
   */
  private void removeItems(int index) {
    ensureItemsIsMutable();
    items_.remove(index);
  }

  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.workout.data.WorkoutSessionItemList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.workout.data.WorkoutSessionItemList prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.WorkoutSessionItemList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.workout.data.WorkoutSessionItemList, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.WorkoutSessionItemList)
      com.ifit.glassos.workout.data.WorkoutSessionItemListOrBuilder {
    // Construct using com.ifit.glassos.workout.data.WorkoutSessionItemList.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.ifit.glassos.workout.data.WorkoutSessionItem> getItemsList() {
      return java.util.Collections.unmodifiableList(
          instance.getItemsList());
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return instance.getItemsCount();
    }/**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    @java.lang.Override
    public com.ifit.glassos.workout.data.WorkoutSessionItem getItems(int index) {
      return instance.getItems(index);
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.ifit.glassos.workout.data.WorkoutSessionItem value) {
      copyOnWrite();
      instance.setItems(index, value);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.ifit.glassos.workout.data.WorkoutSessionItem.Builder builderForValue) {
      copyOnWrite();
      instance.setItems(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder addItems(com.ifit.glassos.workout.data.WorkoutSessionItem value) {
      copyOnWrite();
      instance.addItems(value);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.ifit.glassos.workout.data.WorkoutSessionItem value) {
      copyOnWrite();
      instance.addItems(index, value);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder addItems(
        com.ifit.glassos.workout.data.WorkoutSessionItem.Builder builderForValue) {
      copyOnWrite();
      instance.addItems(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.ifit.glassos.workout.data.WorkoutSessionItem.Builder builderForValue) {
      copyOnWrite();
      instance.addItems(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.ifit.glassos.workout.data.WorkoutSessionItem> values) {
      copyOnWrite();
      instance.addAllItems(values);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder clearItems() {
      copyOnWrite();
      instance.clearItems();
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.WorkoutSessionItem items = 1;</code>
     */
    public Builder removeItems(int index) {
      copyOnWrite();
      instance.removeItems(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.WorkoutSessionItemList)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.workout.data.WorkoutSessionItemList();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "items_",
            com.ifit.glassos.workout.data.WorkoutSessionItem.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.workout.data.WorkoutSessionItemList> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.workout.data.WorkoutSessionItemList.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.workout.data.WorkoutSessionItemList>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.WorkoutSessionItemList)
  private static final com.ifit.glassos.workout.data.WorkoutSessionItemList DEFAULT_INSTANCE;
  static {
    WorkoutSessionItemList defaultInstance = new WorkoutSessionItemList();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      WorkoutSessionItemList.class, defaultInstance);
  }

  public static com.ifit.glassos.workout.data.WorkoutSessionItemList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<WorkoutSessionItemList> PARSER;

  public static com.google.protobuf.Parser<WorkoutSessionItemList> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

