// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appnavigation/TouchEvent.proto

// Protobuf Java Version: 3.25.8
package com.ifit.glassos.appnavigation;

public interface TouchEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.TouchEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
