// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appstore/AppStoreState.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.appstore;

public final class AppStoreStateProto {
  private AppStoreStateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
