// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appstore/AppStoreState.proto

// Protobuf Java Version: 3.25.8
package com.ifit.glassos.appstore;

/**
 * Protobuf type {@code com.ifit.glassos.Error}
 */
public  final class Error extends
    com.google.protobuf.GeneratedMessageLite<
        Error, Error.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.Error)
    ErrorOrBuilder {
  private Error() {
    fqn_ = "";
  }
  private int bitField0_;
  public static final int ERRORCODE_FIELD_NUMBER = 1;
  private int errorCode_;
  /**
   * <code>int32 errorCode = 1;</code>
   * @return The errorCode.
   */
  @java.lang.Override
  public int getErrorCode() {
    return errorCode_;
  }
  /**
   * <code>int32 errorCode = 1;</code>
   * @param value The errorCode to set.
   */
  private void setErrorCode(int value) {
    
    errorCode_ = value;
  }
  /**
   * <code>int32 errorCode = 1;</code>
   */
  private void clearErrorCode() {

    errorCode_ = 0;
  }

  public static final int FQN_FIELD_NUMBER = 2;
  private java.lang.String fqn_;
  /**
   * <code>optional string fqn = 2;</code>
   * @return Whether the fqn field is set.
   */
  @java.lang.Override
  public boolean hasFqn() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string fqn = 2;</code>
   * @return The fqn.
   */
  @java.lang.Override
  public java.lang.String getFqn() {
    return fqn_;
  }
  /**
   * <code>optional string fqn = 2;</code>
   * @return The bytes for fqn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFqnBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fqn_);
  }
  /**
   * <code>optional string fqn = 2;</code>
   * @param value The fqn to set.
   */
  private void setFqn(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    fqn_ = value;
  }
  /**
   * <code>optional string fqn = 2;</code>
   */
  private void clearFqn() {
    bitField0_ = (bitField0_ & ~0x00000001);
    fqn_ = getDefaultInstance().getFqn();
  }
  /**
   * <code>optional string fqn = 2;</code>
   * @param value The bytes for fqn to set.
   */
  private void setFqnBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    fqn_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static com.ifit.glassos.appstore.Error parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.appstore.Error parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.appstore.Error parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.appstore.Error parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.appstore.Error prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.Error}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.appstore.Error, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.Error)
      com.ifit.glassos.appstore.ErrorOrBuilder {
    // Construct using com.ifit.glassos.appstore.Error.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    @java.lang.Override
    public int getErrorCode() {
      return instance.getErrorCode();
    }
    /**
     * <code>int32 errorCode = 1;</code>
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(int value) {
      copyOnWrite();
      instance.setErrorCode(value);
      return this;
    }
    /**
     * <code>int32 errorCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {
      copyOnWrite();
      instance.clearErrorCode();
      return this;
    }

    /**
     * <code>optional string fqn = 2;</code>
     * @return Whether the fqn field is set.
     */
    @java.lang.Override
    public boolean hasFqn() {
      return instance.hasFqn();
    }
    /**
     * <code>optional string fqn = 2;</code>
     * @return The fqn.
     */
    @java.lang.Override
    public java.lang.String getFqn() {
      return instance.getFqn();
    }
    /**
     * <code>optional string fqn = 2;</code>
     * @return The bytes for fqn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFqnBytes() {
      return instance.getFqnBytes();
    }
    /**
     * <code>optional string fqn = 2;</code>
     * @param value The fqn to set.
     * @return This builder for chaining.
     */
    public Builder setFqn(
        java.lang.String value) {
      copyOnWrite();
      instance.setFqn(value);
      return this;
    }
    /**
     * <code>optional string fqn = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFqn() {
      copyOnWrite();
      instance.clearFqn();
      return this;
    }
    /**
     * <code>optional string fqn = 2;</code>
     * @param value The bytes for fqn to set.
     * @return This builder for chaining.
     */
    public Builder setFqnBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFqnBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.Error)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.appstore.Error();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "errorCode_",
            "fqn_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u1208" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.appstore.Error> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.appstore.Error.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.appstore.Error>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.Error)
  private static final com.ifit.glassos.appstore.Error DEFAULT_INSTANCE;
  static {
    Error defaultInstance = new Error();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Error.class, defaultInstance);
  }

  public static com.ifit.glassos.appstore.Error getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Error> PARSER;

  public static com.google.protobuf.Parser<Error> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

