// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: featuregates/FeatureGateResult.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.featuregates;

/**
 * Protobuf type {@code com.ifit.glassos.FeatureGateResult}
 */
public  final class FeatureGateResult extends
    com.google.protobuf.GeneratedMessageLite<
        FeatureGateResult, FeatureGateResult.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.FeatureGateResult)
    FeatureGateResultOrBuilder {
  private FeatureGateResult() {
  }
  private int bitField0_;
  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase {
    BOOLEANVALUE(5),
    USERROLE(6),
    STRINGVALUE(7),
    INTVALUE(8),
    CONSOLETYPE(9),
    USERTIER(10),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 5: return BOOLEANVALUE;
        case 6: return USERROLE;
        case 7: return STRINGVALUE;
        case 8: return INTVALUE;
        case 9: return CONSOLETYPE;
        case 10: return USERTIER;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  private void clearValue() {
    valueCase_ = 0;
    value_ = null;
  }

  public static final int GATEDFEATURE_FIELD_NUMBER = 1;
  private int gatedFeature_;
  /**
   * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
   * @return The enum numeric value on the wire for gatedFeature.
   */
  @java.lang.Override
  public int getGatedFeatureValue() {
    return gatedFeature_;
  }
  /**
   * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
   * @return The gatedFeature.
   */
  @java.lang.Override
  public com.ifit.glassos.featuregates.GatedFeature getGatedFeature() {
    com.ifit.glassos.featuregates.GatedFeature result = com.ifit.glassos.featuregates.GatedFeature.forNumber(gatedFeature_);
    return result == null ? com.ifit.glassos.featuregates.GatedFeature.UNRECOGNIZED : result;
  }
  /**
   * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
   * @param value The enum numeric value on the wire for gatedFeature to set.
   */
  private void setGatedFeatureValue(int value) {
      gatedFeature_ = value;
  }
  /**
   * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
   * @param value The gatedFeature to set.
   */
  private void setGatedFeature(com.ifit.glassos.featuregates.GatedFeature value) {
    gatedFeature_ = value.getNumber();

  }
  /**
   * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
   */
  private void clearGatedFeature() {

    gatedFeature_ = 0;
  }

  public static final int ENABLED_FIELD_NUMBER = 2;
  private boolean enabled_;
  /**
   * <code>bool enabled = 2;</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }
  /**
   * <code>bool enabled = 2;</code>
   * @param value The enabled to set.
   */
  private void setEnabled(boolean value) {
    
    enabled_ = value;
  }
  /**
   * <code>bool enabled = 2;</code>
   */
  private void clearEnabled() {

    enabled_ = false;
  }

  public static final int INCOMPLETE_FIELD_NUMBER = 3;
  private boolean incomplete_;
  /**
   * <code>bool incomplete = 3;</code>
   * @return The incomplete.
   */
  @java.lang.Override
  public boolean getIncomplete() {
    return incomplete_;
  }
  /**
   * <code>bool incomplete = 3;</code>
   * @param value The incomplete to set.
   */
  private void setIncomplete(boolean value) {
    
    incomplete_ = value;
  }
  /**
   * <code>bool incomplete = 3;</code>
   */
  private void clearIncomplete() {

    incomplete_ = false;
  }

  public static final int FEATUREGATEFACET_FIELD_NUMBER = 4;
  private com.ifit.glassos.featuregates.FacetMessage featureGateFacet_;
  /**
   * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
   */
  @java.lang.Override
  public boolean hasFeatureGateFacet() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
   */
  @java.lang.Override
  public com.ifit.glassos.featuregates.FacetMessage getFeatureGateFacet() {
    return featureGateFacet_ == null ? com.ifit.glassos.featuregates.FacetMessage.getDefaultInstance() : featureGateFacet_;
  }
  /**
   * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
   */
  private void setFeatureGateFacet(com.ifit.glassos.featuregates.FacetMessage value) {
    value.getClass();
  featureGateFacet_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeFeatureGateFacet(com.ifit.glassos.featuregates.FacetMessage value) {
    value.getClass();
  if (featureGateFacet_ != null &&
        featureGateFacet_ != com.ifit.glassos.featuregates.FacetMessage.getDefaultInstance()) {
      featureGateFacet_ =
        com.ifit.glassos.featuregates.FacetMessage.newBuilder(featureGateFacet_).mergeFrom(value).buildPartial();
    } else {
      featureGateFacet_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
   */
  private void clearFeatureGateFacet() {  featureGateFacet_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int BOOLEANVALUE_FIELD_NUMBER = 5;
  /**
   * <code>bool booleanValue = 5;</code>
   * @return Whether the booleanValue field is set.
   */
  @java.lang.Override
  public boolean hasBooleanValue() {
    return valueCase_ == 5;
  }
  /**
   * <code>bool booleanValue = 5;</code>
   * @return The booleanValue.
   */
  @java.lang.Override
  public boolean getBooleanValue() {
    if (valueCase_ == 5) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }
  /**
   * <code>bool booleanValue = 5;</code>
   * @param value The booleanValue to set.
   */
  private void setBooleanValue(boolean value) {
    valueCase_ = 5;
    value_ = value;
  }
  /**
   * <code>bool booleanValue = 5;</code>
   */
  private void clearBooleanValue() {
    if (valueCase_ == 5) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int USERROLE_FIELD_NUMBER = 6;
  /**
   * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
   * @return Whether the userRole field is set.
   */
  @java.lang.Override
  public boolean hasUserRole() {
    return valueCase_ == 6;
  }
  /**
   * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
   * @return The enum numeric value on the wire for userRole.
   */
  @java.lang.Override
  public int getUserRoleValue() {
    if (valueCase_ == 6) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }
  /**
   * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
   * @return The userRole.
   */
  @java.lang.Override
  public com.ifit.glassos.club.UserRole getUserRole() {
    if (valueCase_ == 6) {
      com.ifit.glassos.club.UserRole result = com.ifit.glassos.club.UserRole.forNumber((java.lang.Integer) value_);
      return result == null ? com.ifit.glassos.club.UserRole.UNRECOGNIZED : result;
    }
    return com.ifit.glassos.club.UserRole.HOME_USER;
  }
  /**
   * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
   * @param value The enum numeric value on the wire for userRole to set.
   */
  private void setUserRoleValue(int value) {
    valueCase_ = 6;
    value_ = value;
  }
  /**
   * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
   * @param value The userRole to set.
   */
  private void setUserRole(com.ifit.glassos.club.UserRole value) {
    value_ = value.getNumber();
    valueCase_ = 6;
  }
  /**
   * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
   */
  private void clearUserRole() {
    if (valueCase_ == 6) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int STRINGVALUE_FIELD_NUMBER = 7;
  /**
   * <code>string stringValue = 7;</code>
   * @return Whether the stringValue field is set.
   */
  @java.lang.Override
  public boolean hasStringValue() {
    return valueCase_ == 7;
  }
  /**
   * <code>string stringValue = 7;</code>
   * @return The stringValue.
   */
  @java.lang.Override
  public java.lang.String getStringValue() {
    java.lang.String ref = "";
    if (valueCase_ == 7) {
      ref = (java.lang.String) value_;
    }
    return ref;
  }
  /**
   * <code>string stringValue = 7;</code>
   * @return The bytes for stringValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.String ref = "";
    if (valueCase_ == 7) {
      ref = (java.lang.String) value_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string stringValue = 7;</code>
   * @param value The stringValue to set.
   */
  private void setStringValue(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  valueCase_ = 7;
    value_ = value;
  }
  /**
   * <code>string stringValue = 7;</code>
   */
  private void clearStringValue() {
    if (valueCase_ == 7) {
      valueCase_ = 0;
      value_ = null;
    }
  }
  /**
   * <code>string stringValue = 7;</code>
   * @param value The bytes for stringValue to set.
   */
  private void setStringValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    value_ = value.toStringUtf8();
    valueCase_ = 7;
  }

  public static final int INTVALUE_FIELD_NUMBER = 8;
  /**
   * <code>int32 intValue = 8;</code>
   * @return Whether the intValue field is set.
   */
  @java.lang.Override
  public boolean hasIntValue() {
    return valueCase_ == 8;
  }
  /**
   * <code>int32 intValue = 8;</code>
   * @return The intValue.
   */
  @java.lang.Override
  public int getIntValue() {
    if (valueCase_ == 8) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }
  /**
   * <code>int32 intValue = 8;</code>
   * @param value The intValue to set.
   */
  private void setIntValue(int value) {
    valueCase_ = 8;
    value_ = value;
  }
  /**
   * <code>int32 intValue = 8;</code>
   */
  private void clearIntValue() {
    if (valueCase_ == 8) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int CONSOLETYPE_FIELD_NUMBER = 9;
  /**
   * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
   * @return Whether the consoleType field is set.
   */
  @java.lang.Override
  public boolean hasConsoleType() {
    return valueCase_ == 9;
  }
  /**
   * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
   * @return The enum numeric value on the wire for consoleType.
   */
  @java.lang.Override
  public int getConsoleTypeValue() {
    if (valueCase_ == 9) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }
  /**
   * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
   * @return The consoleType.
   */
  @java.lang.Override
  public com.ifit.glassos.console.ConsoleType getConsoleType() {
    if (valueCase_ == 9) {
      com.ifit.glassos.console.ConsoleType result = com.ifit.glassos.console.ConsoleType.forNumber((java.lang.Integer) value_);
      return result == null ? com.ifit.glassos.console.ConsoleType.UNRECOGNIZED : result;
    }
    return com.ifit.glassos.console.ConsoleType.CONSOLE_TYPE_UNKNOWN;
  }
  /**
   * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
   * @param value The enum numeric value on the wire for consoleType to set.
   */
  private void setConsoleTypeValue(int value) {
    valueCase_ = 9;
    value_ = value;
  }
  /**
   * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
   * @param value The consoleType to set.
   */
  private void setConsoleType(com.ifit.glassos.console.ConsoleType value) {
    value_ = value.getNumber();
    valueCase_ = 9;
  }
  /**
   * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
   */
  private void clearConsoleType() {
    if (valueCase_ == 9) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int USERTIER_FIELD_NUMBER = 10;
  /**
   * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
   * @return Whether the userTier field is set.
   */
  @java.lang.Override
  public boolean hasUserTier() {
    return valueCase_ == 10;
  }
  /**
   * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
   * @return The enum numeric value on the wire for userTier.
   */
  @java.lang.Override
  public int getUserTierValue() {
    if (valueCase_ == 10) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }
  /**
   * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
   * @return The userTier.
   */
  @java.lang.Override
  public com.ifit.glassos.user.UserTier getUserTier() {
    if (valueCase_ == 10) {
      com.ifit.glassos.user.UserTier result = com.ifit.glassos.user.UserTier.forNumber((java.lang.Integer) value_);
      return result == null ? com.ifit.glassos.user.UserTier.UNRECOGNIZED : result;
    }
    return com.ifit.glassos.user.UserTier.USER_TIER_UNKNOWN;
  }
  /**
   * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
   * @param value The enum numeric value on the wire for userTier to set.
   */
  private void setUserTierValue(int value) {
    valueCase_ = 10;
    value_ = value;
  }
  /**
   * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
   * @param value The userTier to set.
   */
  private void setUserTier(com.ifit.glassos.user.UserTier value) {
    value_ = value.getNumber();
    valueCase_ = 10;
  }
  /**
   * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
   */
  private void clearUserTier() {
    if (valueCase_ == 10) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.featuregates.FeatureGateResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.featuregates.FeatureGateResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.featuregates.FeatureGateResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.featuregates.FeatureGateResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.FeatureGateResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.featuregates.FeatureGateResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.FeatureGateResult)
      com.ifit.glassos.featuregates.FeatureGateResultOrBuilder {
    // Construct using com.ifit.glassos.featuregates.FeatureGateResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ValueCase
        getValueCase() {
      return instance.getValueCase();
    }

    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }


    /**
     * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
     * @return The enum numeric value on the wire for gatedFeature.
     */
    @java.lang.Override
    public int getGatedFeatureValue() {
      return instance.getGatedFeatureValue();
    }
    /**
     * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
     * @param value The gatedFeature to set.
     * @return This builder for chaining.
     */
    public Builder setGatedFeatureValue(int value) {
      copyOnWrite();
      instance.setGatedFeatureValue(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
     * @return The gatedFeature.
     */
    @java.lang.Override
    public com.ifit.glassos.featuregates.GatedFeature getGatedFeature() {
      return instance.getGatedFeature();
    }
    /**
     * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
     * @param value The enum numeric value on the wire for gatedFeature to set.
     * @return This builder for chaining.
     */
    public Builder setGatedFeature(com.ifit.glassos.featuregates.GatedFeature value) {
      copyOnWrite();
      instance.setGatedFeature(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.GatedFeature gatedFeature = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGatedFeature() {
      copyOnWrite();
      instance.clearGatedFeature();
      return this;
    }

    /**
     * <code>bool enabled = 2;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return instance.getEnabled();
    }
    /**
     * <code>bool enabled = 2;</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {
      copyOnWrite();
      instance.setEnabled(value);
      return this;
    }
    /**
     * <code>bool enabled = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      copyOnWrite();
      instance.clearEnabled();
      return this;
    }

    /**
     * <code>bool incomplete = 3;</code>
     * @return The incomplete.
     */
    @java.lang.Override
    public boolean getIncomplete() {
      return instance.getIncomplete();
    }
    /**
     * <code>bool incomplete = 3;</code>
     * @param value The incomplete to set.
     * @return This builder for chaining.
     */
    public Builder setIncomplete(boolean value) {
      copyOnWrite();
      instance.setIncomplete(value);
      return this;
    }
    /**
     * <code>bool incomplete = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncomplete() {
      copyOnWrite();
      instance.clearIncomplete();
      return this;
    }

    /**
     * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
     */
    @java.lang.Override
    public boolean hasFeatureGateFacet() {
      return instance.hasFeatureGateFacet();
    }
    /**
     * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
     */
    @java.lang.Override
    public com.ifit.glassos.featuregates.FacetMessage getFeatureGateFacet() {
      return instance.getFeatureGateFacet();
    }
    /**
     * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
     */
    public Builder setFeatureGateFacet(com.ifit.glassos.featuregates.FacetMessage value) {
      copyOnWrite();
      instance.setFeatureGateFacet(value);
      return this;
      }
    /**
     * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
     */
    public Builder setFeatureGateFacet(
        com.ifit.glassos.featuregates.FacetMessage.Builder builderForValue) {
      copyOnWrite();
      instance.setFeatureGateFacet(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
     */
    public Builder mergeFeatureGateFacet(com.ifit.glassos.featuregates.FacetMessage value) {
      copyOnWrite();
      instance.mergeFeatureGateFacet(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FacetMessage featureGateFacet = 4;</code>
     */
    public Builder clearFeatureGateFacet() {  copyOnWrite();
      instance.clearFeatureGateFacet();
      return this;
    }

    /**
     * <code>bool booleanValue = 5;</code>
     * @return Whether the booleanValue field is set.
     */
    @java.lang.Override
    public boolean hasBooleanValue() {
      return instance.hasBooleanValue();
    }
    /**
     * <code>bool booleanValue = 5;</code>
     * @return The booleanValue.
     */
    @java.lang.Override
    public boolean getBooleanValue() {
      return instance.getBooleanValue();
    }
    /**
     * <code>bool booleanValue = 5;</code>
     * @param value The booleanValue to set.
     * @return This builder for chaining.
     */
    public Builder setBooleanValue(boolean value) {
      copyOnWrite();
      instance.setBooleanValue(value);
      return this;
    }
    /**
     * <code>bool booleanValue = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBooleanValue() {
      copyOnWrite();
      instance.clearBooleanValue();
      return this;
    }

    /**
     * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
     * @return Whether the userRole field is set.
     */
    @java.lang.Override
    public boolean hasUserRole() {
      return instance.hasUserRole();
    }
    /**
     * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
     * @return The enum numeric value on the wire for userRole.
     */
    @java.lang.Override
    public int getUserRoleValue() {
      return instance.getUserRoleValue();
    }
    /**
     * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
     * @param value The enum numeric value on the wire for userRole to set.
     * @return This builder for chaining.
     */
    public Builder setUserRoleValue(int value) {
      copyOnWrite();
      instance.setUserRoleValue(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
     * @return The userRole.
     */
    @java.lang.Override
    public com.ifit.glassos.club.UserRole getUserRole() {
      return instance.getUserRole();
    }
    /**
     * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
     * @param value The userRole to set.
     * @return This builder for chaining.
     */
    public Builder setUserRole(com.ifit.glassos.club.UserRole value) {
      copyOnWrite();
      instance.setUserRole(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.club.UserRole userRole = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserRole() {
      copyOnWrite();
      instance.clearUserRole();
      return this;
    }

    /**
     * <code>string stringValue = 7;</code>
     * @return Whether the stringValue field is set.
     */
    @java.lang.Override
    public boolean hasStringValue() {
      return instance.hasStringValue();
    }
    /**
     * <code>string stringValue = 7;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      return instance.getStringValue();
    }
    /**
     * <code>string stringValue = 7;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      return instance.getStringValueBytes();
    }
    /**
     * <code>string stringValue = 7;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setStringValue(value);
      return this;
    }
    /**
     * <code>string stringValue = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      copyOnWrite();
      instance.clearStringValue();
      return this;
    }
    /**
     * <code>string stringValue = 7;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStringValueBytes(value);
      return this;
    }

    /**
     * <code>int32 intValue = 8;</code>
     * @return Whether the intValue field is set.
     */
    @java.lang.Override
    public boolean hasIntValue() {
      return instance.hasIntValue();
    }
    /**
     * <code>int32 intValue = 8;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public int getIntValue() {
      return instance.getIntValue();
    }
    /**
     * <code>int32 intValue = 8;</code>
     * @param value The intValue to set.
     * @return This builder for chaining.
     */
    public Builder setIntValue(int value) {
      copyOnWrite();
      instance.setIntValue(value);
      return this;
    }
    /**
     * <code>int32 intValue = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntValue() {
      copyOnWrite();
      instance.clearIntValue();
      return this;
    }

    /**
     * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
     * @return Whether the consoleType field is set.
     */
    @java.lang.Override
    public boolean hasConsoleType() {
      return instance.hasConsoleType();
    }
    /**
     * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
     * @return The enum numeric value on the wire for consoleType.
     */
    @java.lang.Override
    public int getConsoleTypeValue() {
      return instance.getConsoleTypeValue();
    }
    /**
     * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
     * @param value The enum numeric value on the wire for consoleType to set.
     * @return This builder for chaining.
     */
    public Builder setConsoleTypeValue(int value) {
      copyOnWrite();
      instance.setConsoleTypeValue(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
     * @return The consoleType.
     */
    @java.lang.Override
    public com.ifit.glassos.console.ConsoleType getConsoleType() {
      return instance.getConsoleType();
    }
    /**
     * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
     * @param value The consoleType to set.
     * @return This builder for chaining.
     */
    public Builder setConsoleType(com.ifit.glassos.console.ConsoleType value) {
      copyOnWrite();
      instance.setConsoleType(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.ConsoleType consoleType = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsoleType() {
      copyOnWrite();
      instance.clearConsoleType();
      return this;
    }

    /**
     * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
     * @return Whether the userTier field is set.
     */
    @java.lang.Override
    public boolean hasUserTier() {
      return instance.hasUserTier();
    }
    /**
     * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
     * @return The enum numeric value on the wire for userTier.
     */
    @java.lang.Override
    public int getUserTierValue() {
      return instance.getUserTierValue();
    }
    /**
     * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
     * @param value The enum numeric value on the wire for userTier to set.
     * @return This builder for chaining.
     */
    public Builder setUserTierValue(int value) {
      copyOnWrite();
      instance.setUserTierValue(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
     * @return The userTier.
     */
    @java.lang.Override
    public com.ifit.glassos.user.UserTier getUserTier() {
      return instance.getUserTier();
    }
    /**
     * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
     * @param value The userTier to set.
     * @return This builder for chaining.
     */
    public Builder setUserTier(com.ifit.glassos.user.UserTier value) {
      copyOnWrite();
      instance.setUserTier(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.UserTier userTier = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserTier() {
      copyOnWrite();
      instance.clearUserTier();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.FeatureGateResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.featuregates.FeatureGateResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "value_",
            "valueCase_",
            "bitField0_",
            "gatedFeature_",
            "enabled_",
            "incomplete_",
            "featureGateFacet_",
          };
          java.lang.String info =
              "\u0000\n\u0001\u0001\u0001\n\n\u0000\u0000\u0000\u0001\f\u0002\u0007\u0003\u0007" +
              "\u0004\u1009\u0000\u0005:\u0000\u0006?\u0000\u0007\u023b\u0000\b7\u0000\t?\u0000" +
              "\n?\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.featuregates.FeatureGateResult> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.featuregates.FeatureGateResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.featuregates.FeatureGateResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.FeatureGateResult)
  private static final com.ifit.glassos.featuregates.FeatureGateResult DEFAULT_INSTANCE;
  static {
    FeatureGateResult defaultInstance = new FeatureGateResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FeatureGateResult.class, defaultInstance);
  }

  public static com.ifit.glassos.featuregates.FeatureGateResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FeatureGateResult> PARSER;

  public static com.google.protobuf.Parser<FeatureGateResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

