// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/ElevationService.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout;

public interface ElevationMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.ElevationMetric)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string workoutID = 1;</code>
   * @return The workoutID.
   */
  java.lang.String getWorkoutID();
  /**
   * <code>string workoutID = 1;</code>
   * @return The bytes for workoutID.
   */
  com.google.protobuf.ByteString
      getWorkoutIDBytes();

  /**
   * <code>int32 timeSeconds = 2;</code>
   * @return The timeSeconds.
   */
  int getTimeSeconds();

  /**
   * <code>double elevationGainMeters = 3;</code>
   * @return The elevationGainMeters.
   */
  double getElevationGainMeters();

  /**
   * <code>double elevationLossMeters = 4;</code>
   * @return The elevationLossMeters.
   */
  double getElevationLossMeters();

  /**
   * <code>double elevationNetMeters = 5;</code>
   * @return The elevationNetMeters.
   */
  double getElevationNetMeters();
}
