// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/FiveHundredSplitService.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout;

public interface FiveHundredSplitMetricListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.FiveHundredSplitMetricList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .com.ifit.glassos.FiveHundredSplitMetric metrics = 1;</code>
   */
  java.util.List<com.ifit.glassos.workout.FiveHundredSplitMetric> 
      getMetricsList();
  /**
   * <code>repeated .com.ifit.glassos.FiveHundredSplitMetric metrics = 1;</code>
   */
  com.ifit.glassos.workout.FiveHundredSplitMetric getMetrics(int index);
  /**
   * <code>repeated .com.ifit.glassos.FiveHundredSplitMetric metrics = 1;</code>
   */
  int getMetricsCount();
}
