// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workout/GearService.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.workout;

public interface GearMetricListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.GearMetricList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .com.ifit.glassos.GearMetric metrics = 1;</code>
   */
  java.util.List<com.ifit.glassos.workout.GearMetric> 
      getMetricsList();
  /**
   * <code>repeated .com.ifit.glassos.GearMetric metrics = 1;</code>
   */
  com.ifit.glassos.workout.GearMetric getMetrics(int index);
  /**
   * <code>repeated .com.ifit.glassos.GearMetric metrics = 1;</code>
   */
  int getMetricsCount();
}
