// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bluetooth/BluetoothDevice.proto

// Protobuf Java Version: 3.25.8
package com.ifit.glassos.bluetooth;

/**
 * Protobuf type {@code com.ifit.glassos.DeviceBatteryLevelResult}
 */
public  final class DeviceBatteryLevelResult extends
    com.google.protobuf.GeneratedMessageLite<
        DeviceBatteryLevelResult, DeviceBatteryLevelResult.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.DeviceBatteryLevelResult)
    DeviceBatteryLevelResultOrBuilder {
  private DeviceBatteryLevelResult() {
  }
  public static final int BATTERYLEVEL_FIELD_NUMBER = 1;
  private int batteryLevel_;
  /**
   * <code>int32 batteryLevel = 1;</code>
   * @return The batteryLevel.
   */
  @java.lang.Override
  public int getBatteryLevel() {
    return batteryLevel_;
  }
  /**
   * <code>int32 batteryLevel = 1;</code>
   * @param value The batteryLevel to set.
   */
  private void setBatteryLevel(int value) {
    
    batteryLevel_ = value;
  }
  /**
   * <code>int32 batteryLevel = 1;</code>
   */
  private void clearBatteryLevel() {

    batteryLevel_ = 0;
  }

  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.bluetooth.DeviceBatteryLevelResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.DeviceBatteryLevelResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.bluetooth.DeviceBatteryLevelResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.DeviceBatteryLevelResult)
      com.ifit.glassos.bluetooth.DeviceBatteryLevelResultOrBuilder {
    // Construct using com.ifit.glassos.bluetooth.DeviceBatteryLevelResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 batteryLevel = 1;</code>
     * @return The batteryLevel.
     */
    @java.lang.Override
    public int getBatteryLevel() {
      return instance.getBatteryLevel();
    }
    /**
     * <code>int32 batteryLevel = 1;</code>
     * @param value The batteryLevel to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryLevel(int value) {
      copyOnWrite();
      instance.setBatteryLevel(value);
      return this;
    }
    /**
     * <code>int32 batteryLevel = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryLevel() {
      copyOnWrite();
      instance.clearBatteryLevel();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.DeviceBatteryLevelResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.bluetooth.DeviceBatteryLevelResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "batteryLevel_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.bluetooth.DeviceBatteryLevelResult> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.bluetooth.DeviceBatteryLevelResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.bluetooth.DeviceBatteryLevelResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.DeviceBatteryLevelResult)
  private static final com.ifit.glassos.bluetooth.DeviceBatteryLevelResult DEFAULT_INSTANCE;
  static {
    DeviceBatteryLevelResult defaultInstance = new DeviceBatteryLevelResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DeviceBatteryLevelResult.class, defaultInstance);
  }

  public static com.ifit.glassos.bluetooth.DeviceBatteryLevelResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeviceBatteryLevelResult> PARSER;

  public static com.google.protobuf.Parser<DeviceBatteryLevelResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

