// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: console/update/FirmwareUpdateStatus.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.console.update;

/**
 * Protobuf type {@code com.ifit.glassos.FirmwareUpdateStatus}
 */
public  final class FirmwareUpdateStatus extends
    com.google.protobuf.GeneratedMessageLite<
        FirmwareUpdateStatus, FirmwareUpdateStatus.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.FirmwareUpdateStatus)
    FirmwareUpdateStatusOrBuilder {
  private FirmwareUpdateStatus() {
    updateSessionId_ = "";
    resultMessage_ = "";
  }
  private int bitField0_;
  public static final int STATE_FIELD_NUMBER = 1;
  private int state_;
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
   * @return The state.
   */
  @java.lang.Override
  public com.ifit.glassos.console.update.FirmwareUpdateState getState() {
    com.ifit.glassos.console.update.FirmwareUpdateState result = com.ifit.glassos.console.update.FirmwareUpdateState.forNumber(state_);
    return result == null ? com.ifit.glassos.console.update.FirmwareUpdateState.UNRECOGNIZED : result;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
   * @param value The enum numeric value on the wire for state to set.
   */
  private void setStateValue(int value) {
      state_ = value;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
   * @param value The state to set.
   */
  private void setState(com.ifit.glassos.console.update.FirmwareUpdateState value) {
    state_ = value.getNumber();

  }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
   */
  private void clearState() {

    state_ = 0;
  }

  public static final int UPDATESESSIONID_FIELD_NUMBER = 2;
  private java.lang.String updateSessionId_;
  /**
   * <code>string updateSessionId = 2;</code>
   * @return The updateSessionId.
   */
  @java.lang.Override
  public java.lang.String getUpdateSessionId() {
    return updateSessionId_;
  }
  /**
   * <code>string updateSessionId = 2;</code>
   * @return The bytes for updateSessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdateSessionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(updateSessionId_);
  }
  /**
   * <code>string updateSessionId = 2;</code>
   * @param value The updateSessionId to set.
   */
  private void setUpdateSessionId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    updateSessionId_ = value;
  }
  /**
   * <code>string updateSessionId = 2;</code>
   */
  private void clearUpdateSessionId() {

    updateSessionId_ = getDefaultInstance().getUpdateSessionId();
  }
  /**
   * <code>string updateSessionId = 2;</code>
   * @param value The bytes for updateSessionId to set.
   */
  private void setUpdateSessionIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    updateSessionId_ = value.toStringUtf8();

  }

  public static final int UPDATEFILE_FIELD_NUMBER = 3;
  private com.ifit.glassos.console.update.FirmwareUpdateFile updateFile_;
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
   */
  @java.lang.Override
  public boolean hasUpdateFile() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
   */
  @java.lang.Override
  public com.ifit.glassos.console.update.FirmwareUpdateFile getUpdateFile() {
    return updateFile_ == null ? com.ifit.glassos.console.update.FirmwareUpdateFile.getDefaultInstance() : updateFile_;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
   */
  private void setUpdateFile(com.ifit.glassos.console.update.FirmwareUpdateFile value) {
    value.getClass();
  updateFile_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUpdateFile(com.ifit.glassos.console.update.FirmwareUpdateFile value) {
    value.getClass();
  if (updateFile_ != null &&
        updateFile_ != com.ifit.glassos.console.update.FirmwareUpdateFile.getDefaultInstance()) {
      updateFile_ =
        com.ifit.glassos.console.update.FirmwareUpdateFile.newBuilder(updateFile_).mergeFrom(value).buildPartial();
    } else {
      updateFile_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
   */
  private void clearUpdateFile() {  updateFile_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int STARTTIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp startTime_;
  /**
   * <code>.google.protobuf.Timestamp startTime = 4;</code>
   */
  @java.lang.Override
  public boolean hasStartTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp startTime = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getStartTime() {
    return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp startTime = 4;</code>
   */
  private void setStartTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  startTime_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>.google.protobuf.Timestamp startTime = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeStartTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (startTime_ != null &&
        startTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      startTime_ =
        com.google.protobuf.Timestamp.newBuilder(startTime_).mergeFrom(value).buildPartial();
    } else {
      startTime_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.google.protobuf.Timestamp startTime = 4;</code>
   */
  private void clearStartTime() {  startTime_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int ENDTIME_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp endTime_;
  /**
   * <code>.google.protobuf.Timestamp endTime = 5;</code>
   */
  @java.lang.Override
  public boolean hasEndTime() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp endTime = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEndTime() {
    return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp endTime = 5;</code>
   */
  private void setEndTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  endTime_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <code>.google.protobuf.Timestamp endTime = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeEndTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (endTime_ != null &&
        endTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      endTime_ =
        com.google.protobuf.Timestamp.newBuilder(endTime_).mergeFrom(value).buildPartial();
    } else {
      endTime_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>.google.protobuf.Timestamp endTime = 5;</code>
   */
  private void clearEndTime() {  endTime_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int RESULTMESSAGE_FIELD_NUMBER = 6;
  private java.lang.String resultMessage_;
  /**
   * <code>string resultMessage = 6;</code>
   * @return The resultMessage.
   */
  @java.lang.Override
  public java.lang.String getResultMessage() {
    return resultMessage_;
  }
  /**
   * <code>string resultMessage = 6;</code>
   * @return The bytes for resultMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(resultMessage_);
  }
  /**
   * <code>string resultMessage = 6;</code>
   * @param value The resultMessage to set.
   */
  private void setResultMessage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    resultMessage_ = value;
  }
  /**
   * <code>string resultMessage = 6;</code>
   */
  private void clearResultMessage() {

    resultMessage_ = getDefaultInstance().getResultMessage();
  }
  /**
   * <code>string resultMessage = 6;</code>
   * @param value The bytes for resultMessage to set.
   */
  private void setResultMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    resultMessage_ = value.toStringUtf8();

  }

  public static final int PERCENTCOMPLETE_FIELD_NUMBER = 7;
  private float percentComplete_;
  /**
   * <code>float percentComplete = 7;</code>
   * @return The percentComplete.
   */
  @java.lang.Override
  public float getPercentComplete() {
    return percentComplete_;
  }
  /**
   * <code>float percentComplete = 7;</code>
   * @param value The percentComplete to set.
   */
  private void setPercentComplete(float value) {
    
    percentComplete_ = value;
  }
  /**
   * <code>float percentComplete = 7;</code>
   */
  private void clearPercentComplete() {

    percentComplete_ = 0F;
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.console.update.FirmwareUpdateStatus prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.FirmwareUpdateStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.console.update.FirmwareUpdateStatus, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.FirmwareUpdateStatus)
      com.ifit.glassos.console.update.FirmwareUpdateStatusOrBuilder {
    // Construct using com.ifit.glassos.console.update.FirmwareUpdateStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override
    public int getStateValue() {
      return instance.getStateValue();
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      copyOnWrite();
      instance.setStateValue(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.ifit.glassos.console.update.FirmwareUpdateState getState() {
      return instance.getState();
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.ifit.glassos.console.update.FirmwareUpdateState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateState state = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <code>string updateSessionId = 2;</code>
     * @return The updateSessionId.
     */
    @java.lang.Override
    public java.lang.String getUpdateSessionId() {
      return instance.getUpdateSessionId();
    }
    /**
     * <code>string updateSessionId = 2;</code>
     * @return The bytes for updateSessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpdateSessionIdBytes() {
      return instance.getUpdateSessionIdBytes();
    }
    /**
     * <code>string updateSessionId = 2;</code>
     * @param value The updateSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateSessionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpdateSessionId(value);
      return this;
    }
    /**
     * <code>string updateSessionId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateSessionId() {
      copyOnWrite();
      instance.clearUpdateSessionId();
      return this;
    }
    /**
     * <code>string updateSessionId = 2;</code>
     * @param value The bytes for updateSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateSessionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpdateSessionIdBytes(value);
      return this;
    }

    /**
     * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
     */
    @java.lang.Override
    public boolean hasUpdateFile() {
      return instance.hasUpdateFile();
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
     */
    @java.lang.Override
    public com.ifit.glassos.console.update.FirmwareUpdateFile getUpdateFile() {
      return instance.getUpdateFile();
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
     */
    public Builder setUpdateFile(com.ifit.glassos.console.update.FirmwareUpdateFile value) {
      copyOnWrite();
      instance.setUpdateFile(value);
      return this;
      }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
     */
    public Builder setUpdateFile(
        com.ifit.glassos.console.update.FirmwareUpdateFile.Builder builderForValue) {
      copyOnWrite();
      instance.setUpdateFile(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
     */
    public Builder mergeUpdateFile(com.ifit.glassos.console.update.FirmwareUpdateFile value) {
      copyOnWrite();
      instance.mergeUpdateFile(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FirmwareUpdateFile updateFile = 3;</code>
     */
    public Builder clearUpdateFile() {  copyOnWrite();
      instance.clearUpdateFile();
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    @java.lang.Override
    public boolean hasStartTime() {
      return instance.hasStartTime();
    }
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getStartTime() {
      return instance.getStartTime();
    }
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    public Builder setStartTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setStartTime(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    public Builder setStartTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setStartTime(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    public Builder mergeStartTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeStartTime(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startTime = 4;</code>
     */
    public Builder clearStartTime() {  copyOnWrite();
      instance.clearStartTime();
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    @java.lang.Override
    public boolean hasEndTime() {
      return instance.hasEndTime();
    }
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEndTime() {
      return instance.getEndTime();
    }
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    public Builder setEndTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setEndTime(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    public Builder setEndTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setEndTime(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    public Builder mergeEndTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeEndTime(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endTime = 5;</code>
     */
    public Builder clearEndTime() {  copyOnWrite();
      instance.clearEndTime();
      return this;
    }

    /**
     * <code>string resultMessage = 6;</code>
     * @return The resultMessage.
     */
    @java.lang.Override
    public java.lang.String getResultMessage() {
      return instance.getResultMessage();
    }
    /**
     * <code>string resultMessage = 6;</code>
     * @return The bytes for resultMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultMessageBytes() {
      return instance.getResultMessageBytes();
    }
    /**
     * <code>string resultMessage = 6;</code>
     * @param value The resultMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResultMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setResultMessage(value);
      return this;
    }
    /**
     * <code>string resultMessage = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultMessage() {
      copyOnWrite();
      instance.clearResultMessage();
      return this;
    }
    /**
     * <code>string resultMessage = 6;</code>
     * @param value The bytes for resultMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResultMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResultMessageBytes(value);
      return this;
    }

    /**
     * <code>float percentComplete = 7;</code>
     * @return The percentComplete.
     */
    @java.lang.Override
    public float getPercentComplete() {
      return instance.getPercentComplete();
    }
    /**
     * <code>float percentComplete = 7;</code>
     * @param value The percentComplete to set.
     * @return This builder for chaining.
     */
    public Builder setPercentComplete(float value) {
      copyOnWrite();
      instance.setPercentComplete(value);
      return this;
    }
    /**
     * <code>float percentComplete = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPercentComplete() {
      copyOnWrite();
      instance.clearPercentComplete();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.FirmwareUpdateStatus)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.console.update.FirmwareUpdateStatus();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "state_",
            "updateSessionId_",
            "updateFile_",
            "startTime_",
            "endTime_",
            "resultMessage_",
            "percentComplete_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "\u0003\u1009\u0000\u0004\u1009\u0001\u0005\u1009\u0002\u0006\u0208\u0007\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.console.update.FirmwareUpdateStatus> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.console.update.FirmwareUpdateStatus.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.console.update.FirmwareUpdateStatus>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.FirmwareUpdateStatus)
  private static final com.ifit.glassos.console.update.FirmwareUpdateStatus DEFAULT_INSTANCE;
  static {
    FirmwareUpdateStatus defaultInstance = new FirmwareUpdateStatus();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FirmwareUpdateStatus.class, defaultInstance);
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FirmwareUpdateStatus> PARSER;

  public static com.google.protobuf.Parser<FirmwareUpdateStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

