// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: console/update/FirmwareUpdateFile.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.console.update;

/**
 * Protobuf type {@code com.ifit.glassos.FirmwareUpdateFile}
 */
public  final class FirmwareUpdateFile extends
    com.google.protobuf.GeneratedMessageLite<
        FirmwareUpdateFile, FirmwareUpdateFile.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.FirmwareUpdateFile)
    FirmwareUpdateFileOrBuilder {
  private FirmwareUpdateFile() {
    filePath_ = "";
    fileName_ = "";
    version_ = "";
  }
  public static final int UPDATETYPE_FIELD_NUMBER = 1;
  private int updateType_;
  /**
   * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
   * @return The enum numeric value on the wire for updateType.
   */
  @java.lang.Override
  public int getUpdateTypeValue() {
    return updateType_;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
   * @return The updateType.
   */
  @java.lang.Override
  public com.ifit.glassos.console.update.FirmwareType getUpdateType() {
    com.ifit.glassos.console.update.FirmwareType result = com.ifit.glassos.console.update.FirmwareType.forNumber(updateType_);
    return result == null ? com.ifit.glassos.console.update.FirmwareType.UNRECOGNIZED : result;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
   * @param value The enum numeric value on the wire for updateType to set.
   */
  private void setUpdateTypeValue(int value) {
      updateType_ = value;
  }
  /**
   * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
   * @param value The updateType to set.
   */
  private void setUpdateType(com.ifit.glassos.console.update.FirmwareType value) {
    updateType_ = value.getNumber();

  }
  /**
   * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
   */
  private void clearUpdateType() {

    updateType_ = 0;
  }

  public static final int FILEPATH_FIELD_NUMBER = 2;
  private java.lang.String filePath_;
  /**
   * <code>string filePath = 2;</code>
   * @return The filePath.
   */
  @java.lang.Override
  public java.lang.String getFilePath() {
    return filePath_;
  }
  /**
   * <code>string filePath = 2;</code>
   * @return The bytes for filePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilePathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(filePath_);
  }
  /**
   * <code>string filePath = 2;</code>
   * @param value The filePath to set.
   */
  private void setFilePath(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    filePath_ = value;
  }
  /**
   * <code>string filePath = 2;</code>
   */
  private void clearFilePath() {

    filePath_ = getDefaultInstance().getFilePath();
  }
  /**
   * <code>string filePath = 2;</code>
   * @param value The bytes for filePath to set.
   */
  private void setFilePathBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    filePath_ = value.toStringUtf8();

  }

  public static final int FILENAME_FIELD_NUMBER = 3;
  private java.lang.String fileName_;
  /**
   * <code>string fileName = 3;</code>
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    return fileName_;
  }
  /**
   * <code>string fileName = 3;</code>
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fileName_);
  }
  /**
   * <code>string fileName = 3;</code>
   * @param value The fileName to set.
   */
  private void setFileName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    fileName_ = value;
  }
  /**
   * <code>string fileName = 3;</code>
   */
  private void clearFileName() {

    fileName_ = getDefaultInstance().getFileName();
  }
  /**
   * <code>string fileName = 3;</code>
   * @param value The bytes for fileName to set.
   */
  private void setFileNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    fileName_ = value.toStringUtf8();

  }

  public static final int VERSION_FIELD_NUMBER = 4;
  private java.lang.String version_;
  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    return version_;
  }
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(version_);
  }
  /**
   * <code>string version = 4;</code>
   * @param value The version to set.
   */
  private void setVersion(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    version_ = value;
  }
  /**
   * <code>string version = 4;</code>
   */
  private void clearVersion() {

    version_ = getDefaultInstance().getVersion();
  }
  /**
   * <code>string version = 4;</code>
   * @param value The bytes for version to set.
   */
  private void setVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    version_ = value.toStringUtf8();

  }

  public static final int PARTNUMBER_FIELD_NUMBER = 5;
  private int partNumber_;
  /**
   * <code>int32 partNumber = 5;</code>
   * @return The partNumber.
   */
  @java.lang.Override
  public int getPartNumber() {
    return partNumber_;
  }
  /**
   * <code>int32 partNumber = 5;</code>
   * @param value The partNumber to set.
   */
  private void setPartNumber(int value) {
    
    partNumber_ = value;
  }
  /**
   * <code>int32 partNumber = 5;</code>
   */
  private void clearPartNumber() {

    partNumber_ = 0;
  }

  public static final int FORCEUPDATE_FIELD_NUMBER = 6;
  private boolean forceUpdate_;
  /**
   * <code>bool forceUpdate = 6;</code>
   * @return The forceUpdate.
   */
  @java.lang.Override
  public boolean getForceUpdate() {
    return forceUpdate_;
  }
  /**
   * <code>bool forceUpdate = 6;</code>
   * @param value The forceUpdate to set.
   */
  private void setForceUpdate(boolean value) {
    
    forceUpdate_ = value;
  }
  /**
   * <code>bool forceUpdate = 6;</code>
   */
  private void clearForceUpdate() {

    forceUpdate_ = false;
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.console.update.FirmwareUpdateFile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.console.update.FirmwareUpdateFile prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.FirmwareUpdateFile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.console.update.FirmwareUpdateFile, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.FirmwareUpdateFile)
      com.ifit.glassos.console.update.FirmwareUpdateFileOrBuilder {
    // Construct using com.ifit.glassos.console.update.FirmwareUpdateFile.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
     * @return The enum numeric value on the wire for updateType.
     */
    @java.lang.Override
    public int getUpdateTypeValue() {
      return instance.getUpdateTypeValue();
    }
    /**
     * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
     * @param value The updateType to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTypeValue(int value) {
      copyOnWrite();
      instance.setUpdateTypeValue(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
     * @return The updateType.
     */
    @java.lang.Override
    public com.ifit.glassos.console.update.FirmwareType getUpdateType() {
      return instance.getUpdateType();
    }
    /**
     * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
     * @param value The enum numeric value on the wire for updateType to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateType(com.ifit.glassos.console.update.FirmwareType value) {
      copyOnWrite();
      instance.setUpdateType(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.FirmwareType updateType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateType() {
      copyOnWrite();
      instance.clearUpdateType();
      return this;
    }

    /**
     * <code>string filePath = 2;</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      return instance.getFilePath();
    }
    /**
     * <code>string filePath = 2;</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      return instance.getFilePathBytes();
    }
    /**
     * <code>string filePath = 2;</code>
     * @param value The filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePath(
        java.lang.String value) {
      copyOnWrite();
      instance.setFilePath(value);
      return this;
    }
    /**
     * <code>string filePath = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilePath() {
      copyOnWrite();
      instance.clearFilePath();
      return this;
    }
    /**
     * <code>string filePath = 2;</code>
     * @param value The bytes for filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFilePathBytes(value);
      return this;
    }

    /**
     * <code>string fileName = 3;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      return instance.getFileName();
    }
    /**
     * <code>string fileName = 3;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      return instance.getFileNameBytes();
    }
    /**
     * <code>string fileName = 3;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      copyOnWrite();
      instance.setFileName(value);
      return this;
    }
    /**
     * <code>string fileName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      copyOnWrite();
      instance.clearFileName();
      return this;
    }
    /**
     * <code>string fileName = 3;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFileNameBytes(value);
      return this;
    }

    /**
     * <code>string version = 4;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>string version = 4;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return instance.getVersionBytes();
    }
    /**
     * <code>string version = 4;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>string version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }
    /**
     * <code>string version = 4;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVersionBytes(value);
      return this;
    }

    /**
     * <code>int32 partNumber = 5;</code>
     * @return The partNumber.
     */
    @java.lang.Override
    public int getPartNumber() {
      return instance.getPartNumber();
    }
    /**
     * <code>int32 partNumber = 5;</code>
     * @param value The partNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPartNumber(int value) {
      copyOnWrite();
      instance.setPartNumber(value);
      return this;
    }
    /**
     * <code>int32 partNumber = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartNumber() {
      copyOnWrite();
      instance.clearPartNumber();
      return this;
    }

    /**
     * <code>bool forceUpdate = 6;</code>
     * @return The forceUpdate.
     */
    @java.lang.Override
    public boolean getForceUpdate() {
      return instance.getForceUpdate();
    }
    /**
     * <code>bool forceUpdate = 6;</code>
     * @param value The forceUpdate to set.
     * @return This builder for chaining.
     */
    public Builder setForceUpdate(boolean value) {
      copyOnWrite();
      instance.setForceUpdate(value);
      return this;
    }
    /**
     * <code>bool forceUpdate = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearForceUpdate() {
      copyOnWrite();
      instance.clearForceUpdate();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.FirmwareUpdateFile)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.console.update.FirmwareUpdateFile();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "updateType_",
            "filePath_",
            "fileName_",
            "version_",
            "partNumber_",
            "forceUpdate_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0004\u0006\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.console.update.FirmwareUpdateFile> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.console.update.FirmwareUpdateFile.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.console.update.FirmwareUpdateFile>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.FirmwareUpdateFile)
  private static final com.ifit.glassos.console.update.FirmwareUpdateFile DEFAULT_INSTANCE;
  static {
    FirmwareUpdateFile defaultInstance = new FirmwareUpdateFile();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FirmwareUpdateFile.class, defaultInstance);
  }

  public static com.ifit.glassos.console.update.FirmwareUpdateFile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FirmwareUpdateFile> PARSER;

  public static com.google.protobuf.Parser<FirmwareUpdateFile> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

