// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: console/ConsoleInfo.proto

// Protobuf Java Version: 3.25.8
package com.ifit.glassos.console;

public interface ConsoleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.ConsoleInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 modelNumber = 1;</code>
   * @return The modelNumber.
   */
  int getModelNumber();

  /**
   * <code>int32 partNumber = 2;</code>
   * @return The partNumber.
   */
  int getPartNumber();

  /**
   * <code>int32 softwareVersion = 3;</code>
   * @return The softwareVersion.
   */
  int getSoftwareVersion();

  /**
   * <code>int32 hardwareVersion = 4;</code>
   * @return The hardwareVersion.
   */
  int getHardwareVersion();

  /**
   * <code>string firmwareVersion = 5;</code>
   * @return The firmwareVersion.
   */
  java.lang.String getFirmwareVersion();
  /**
   * <code>string firmwareVersion = 5;</code>
   * @return The bytes for firmwareVersion.
   */
  com.google.protobuf.ByteString
      getFirmwareVersionBytes();

  /**
   * <code>int32 serialNumber = 6;</code>
   * @return The serialNumber.
   */
  int getSerialNumber();

  /**
   * <code>.com.ifit.glassos.ConsoleType machineType = 7;</code>
   * @return The enum numeric value on the wire for machineType.
   */
  int getMachineTypeValue();
  /**
   * <code>.com.ifit.glassos.ConsoleType machineType = 7;</code>
   * @return The machineType.
   */
  com.ifit.glassos.console.ConsoleType getMachineType();

  /**
   * <code>string name = 8;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 8;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string brainboardSerialNumber = 9;</code>
   * @return The brainboardSerialNumber.
   */
  java.lang.String getBrainboardSerialNumber();
  /**
   * <code>string brainboardSerialNumber = 9;</code>
   * @return The bytes for brainboardSerialNumber.
   */
  com.google.protobuf.ByteString
      getBrainboardSerialNumberBytes();

  /**
   * <code>int32 masterLibraryVersion = 10;</code>
   * @return The masterLibraryVersion.
   */
  int getMasterLibraryVersion();

  /**
   * <code>int32 masterLibraryBuild = 11;</code>
   * @return The masterLibraryBuild.
   */
  int getMasterLibraryBuild();

  /**
   * <code>.com.ifit.glassos.SystemUnits systemUnits = 12;</code>
   * @return The enum numeric value on the wire for systemUnits.
   */
  int getSystemUnitsValue();
  /**
   * <code>.com.ifit.glassos.SystemUnits systemUnits = 12;</code>
   * @return The systemUnits.
   */
  com.ifit.glassos.settings.SystemUnits getSystemUnits();

  /**
   * <code>double maxKph = 13;</code>
   * @return The maxKph.
   */
  double getMaxKph();

  /**
   * <code>double minKph = 14;</code>
   * @return The minKph.
   */
  double getMinKph();

  /**
   * <code>double maxInclinePercent = 15;</code>
   * @return The maxInclinePercent.
   */
  double getMaxInclinePercent();

  /**
   * <code>double minInclinePercent = 16;</code>
   * @return The minInclinePercent.
   */
  double getMinInclinePercent();

  /**
   * <code>double minResistance = 17;</code>
   * @return The minResistance.
   */
  double getMinResistance();

  /**
   * <code>double maxResistance = 18;</code>
   * @return The maxResistance.
   */
  double getMaxResistance();

  /**
   * <code>int32 minGear = 19;</code>
   * @return The minGear.
   */
  int getMinGear();

  /**
   * <code>int32 maxGear = 20;</code>
   * @return The maxGear.
   */
  int getMaxGear();

  /**
   * <code>double maxWeightKg = 21;</code>
   * @return The maxWeightKg.
   */
  double getMaxWeightKg();

  /**
   * <code>bool canSetSpeed = 22;</code>
   * @return The canSetSpeed.
   */
  boolean getCanSetSpeed();

  /**
   * <code>bool canSetIncline = 23;</code>
   * @return The canSetIncline.
   */
  boolean getCanSetIncline();

  /**
   * <code>bool canSetResistance = 24;</code>
   * @return The canSetResistance.
   */
  boolean getCanSetResistance();

  /**
   * <code>bool canSetGear = 25;</code>
   * @return The canSetGear.
   */
  boolean getCanSetGear();

  /**
   * <code>bool canSetActivationLock = 26;</code>
   * @return The canSetActivationLock.
   */
  boolean getCanSetActivationLock();

  /**
   * <code>bool supportsVerticalGain = 27;</code>
   * @return The supportsVerticalGain.
   */
  boolean getSupportsVerticalGain();

  /**
   * <code>bool supportsVerticalNet = 28;</code>
   * @return The supportsVerticalNet.
   */
  boolean getSupportsVerticalNet();

  /**
   * <code>bool supportsStartRequested = 29;</code>
   * @return The supportsStartRequested.
   */
  boolean getSupportsStartRequested();

  /**
   * <code>bool supportsRequireStartRequested = 30;</code>
   * @return The supportsRequireStartRequested.
   */
  boolean getSupportsRequireStartRequested();

  /**
   * <code>bool supportsKeyPressObserved = 31;</code>
   * @return The supportsKeyPressObserved.
   */
  boolean getSupportsKeyPressObserved();

  /**
   * <code>bool supportsPulse = 32;</code>
   * @return The supportsPulse.
   */
  boolean getSupportsPulse();

  /**
   * <code>double totalTimeSeconds = 33;</code>
   * @return The totalTimeSeconds.
   */
  double getTotalTimeSeconds();

  /**
   * <code>double warmUpTimeoutSeconds = 34;</code>
   * @return The warmUpTimeoutSeconds.
   */
  double getWarmUpTimeoutSeconds();

  /**
   * <code>double coolDownTimeoutSeconds = 35;</code>
   * @return The coolDownTimeoutSeconds.
   */
  double getCoolDownTimeoutSeconds();

  /**
   * <code>double pauseTimeoutSeconds = 36;</code>
   * @return The pauseTimeoutSeconds.
   */
  double getPauseTimeoutSeconds();

  /**
   * <code>double totalDistanceKm = 37;</code>
   * @return The totalDistanceKm.
   */
  double getTotalDistanceKm();

  /**
   * <code>bool isClubUnit = 38;</code>
   * @return The isClubUnit.
   */
  boolean getIsClubUnit();

  /**
   * <code>double weightKg = 39;</code>
   * @return The weightKg.
   */
  double getWeightKg();

  /**
   * <code>bool supportsConstantWatts = 40;</code>
   * @return The supportsConstantWatts.
   */
  boolean getSupportsConstantWatts();

  /**
   * <code>string antPlusBootloaderVersion = 41;</code>
   * @return The antPlusBootloaderVersion.
   */
  java.lang.String getAntPlusBootloaderVersion();
  /**
   * <code>string antPlusBootloaderVersion = 41;</code>
   * @return The bytes for antPlusBootloaderVersion.
   */
  com.google.protobuf.ByteString
      getAntPlusBootloaderVersionBytes();

  /**
   * <code>string antPlusSerialNumber = 42;</code>
   * @return The antPlusSerialNumber.
   */
  java.lang.String getAntPlusSerialNumber();
  /**
   * <code>string antPlusSerialNumber = 42;</code>
   * @return The bytes for antPlusSerialNumber.
   */
  com.google.protobuf.ByteString
      getAntPlusSerialNumberBytes();

  /**
   * <code>string antPlusDeviceNumber = 43;</code>
   * @return The antPlusDeviceNumber.
   */
  java.lang.String getAntPlusDeviceNumber();
  /**
   * <code>string antPlusDeviceNumber = 43;</code>
   * @return The bytes for antPlusDeviceNumber.
   */
  com.google.protobuf.ByteString
      getAntPlusDeviceNumberBytes();

  /**
   * <code>string antPlusRelaySoftwareVersion = 44;</code>
   * @return The antPlusRelaySoftwareVersion.
   */
  java.lang.String getAntPlusRelaySoftwareVersion();
  /**
   * <code>string antPlusRelaySoftwareVersion = 44;</code>
   * @return The bytes for antPlusRelaySoftwareVersion.
   */
  com.google.protobuf.ByteString
      getAntPlusRelaySoftwareVersionBytes();

  /**
   * <code>string productSerialNumber = 45;</code>
   * @return The productSerialNumber.
   */
  java.lang.String getProductSerialNumber();
  /**
   * <code>string productSerialNumber = 45;</code>
   * @return The bytes for productSerialNumber.
   */
  com.google.protobuf.ByteString
      getProductSerialNumberBytes();

  /**
   * <code>string controller1SoftwareVersion = 46;</code>
   * @return The controller1SoftwareVersion.
   */
  java.lang.String getController1SoftwareVersion();
  /**
   * <code>string controller1SoftwareVersion = 46;</code>
   * @return The bytes for controller1SoftwareVersion.
   */
  com.google.protobuf.ByteString
      getController1SoftwareVersionBytes();

  /**
   * <code>string controller1SoftwarePartNumber = 47;</code>
   * @return The controller1SoftwarePartNumber.
   */
  java.lang.String getController1SoftwarePartNumber();
  /**
   * <code>string controller1SoftwarePartNumber = 47;</code>
   * @return The bytes for controller1SoftwarePartNumber.
   */
  com.google.protobuf.ByteString
      getController1SoftwarePartNumberBytes();

  /**
   * <code>string controller4SoftwareVersion = 48;</code>
   * @return The controller4SoftwareVersion.
   */
  java.lang.String getController4SoftwareVersion();
  /**
   * <code>string controller4SoftwareVersion = 48;</code>
   * @return The bytes for controller4SoftwareVersion.
   */
  com.google.protobuf.ByteString
      getController4SoftwareVersionBytes();

  /**
   * <code>string controller4SoftwarePartNumber = 49;</code>
   * @return The controller4SoftwarePartNumber.
   */
  java.lang.String getController4SoftwarePartNumber();
  /**
   * <code>string controller4SoftwarePartNumber = 49;</code>
   * @return The bytes for controller4SoftwarePartNumber.
   */
  com.google.protobuf.ByteString
      getController4SoftwarePartNumberBytes();

  /**
   * <code>string controller40SoftwareVersion = 50;</code>
   * @return The controller40SoftwareVersion.
   */
  java.lang.String getController40SoftwareVersion();
  /**
   * <code>string controller40SoftwareVersion = 50;</code>
   * @return The bytes for controller40SoftwareVersion.
   */
  com.google.protobuf.ByteString
      getController40SoftwareVersionBytes();

  /**
   * <code>string controller40SoftwarePartNumber = 51;</code>
   * @return The controller40SoftwarePartNumber.
   */
  java.lang.String getController40SoftwarePartNumber();
  /**
   * <code>string controller40SoftwarePartNumber = 51;</code>
   * @return The bytes for controller40SoftwarePartNumber.
   */
  com.google.protobuf.ByteString
      getController40SoftwarePartNumberBytes();
}
