// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: console/tdf/TDFRearCassetteConfig.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.console.tdf;

public final class TDFRearCassetteConfigProto {
  private TDFRearCassetteConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
