// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: console/keypress/KeyPress.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.console.keypress;

public interface KeyPressResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.KeyPressResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.ifit.glassos.IFitError error = 1;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.com.ifit.glassos.IFitError error = 1;</code>
   * @return The error.
   */
  com.ifit.glassos.util.IFitError getError();

  /**
   * <code>.com.ifit.glassos.KeyPress keyPress = 2;</code>
   * @return Whether the keyPress field is set.
   */
  boolean hasKeyPress();
  /**
   * <code>.com.ifit.glassos.KeyPress keyPress = 2;</code>
   * @return The keyPress.
   */
  com.ifit.glassos.console.keypress.KeyPress getKeyPress();

  public com.ifit.glassos.console.keypress.KeyPressResult.ErrorOrKeyPressCase getErrorOrKeyPressCase();
}
