services:
  qdomyos-zwift-vnc:
    image: qdomyos-zwift-vnc
    container_name: qdomyos-zwift-vnc
    privileged: true  # Required for Bluetooth functionality
    network_mode: "host"  # Used to access host Bluetooth and D-Bus
    volumes:
      - /dev:/dev  # Forward host devices (for Bluetooth)
      - /run/dbus:/run/dbus  # Forward D-Bus for Bluetooth interaction
    restart: "no"  # Do not restart the container automatically
