// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antplus/AntPlusService.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.antplus;

public final class AntPlusServiceProto {
  private AntPlusServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
