// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/WarningAcceptance.proto

// Protobuf Java Version: 3.25.8
package com.ifit.glassos.user;

/**
 * Protobuf type {@code com.ifit.glassos.WarningAcceptanceResult}
 */
public  final class WarningAcceptanceResult extends
    com.google.protobuf.GeneratedMessageLite<
        WarningAcceptanceResult, WarningAcceptanceResult.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.WarningAcceptanceResult)
    WarningAcceptanceResultOrBuilder {
  private WarningAcceptanceResult() {
  }
  private int errorOrWarningAcceptanceCase_ = 0;
  private java.lang.Object errorOrWarningAcceptance_;
  public enum ErrorOrWarningAcceptanceCase {
    ERROR(1),
    WARNINGACCEPTANCETIME(2),
    ERRORORWARNINGACCEPTANCE_NOT_SET(0);
    private final int value;
    private ErrorOrWarningAcceptanceCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorOrWarningAcceptanceCase valueOf(int value) {
      return forNumber(value);
    }

    public static ErrorOrWarningAcceptanceCase forNumber(int value) {
      switch (value) {
        case 1: return ERROR;
        case 2: return WARNINGACCEPTANCETIME;
        case 0: return ERRORORWARNINGACCEPTANCE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ErrorOrWarningAcceptanceCase
  getErrorOrWarningAcceptanceCase() {
    return ErrorOrWarningAcceptanceCase.forNumber(
        errorOrWarningAcceptanceCase_);
  }

  private void clearErrorOrWarningAcceptance() {
    errorOrWarningAcceptanceCase_ = 0;
    errorOrWarningAcceptance_ = null;
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  /**
   * <code>.com.ifit.glassos.IFitError error = 1;</code>
   */
  @java.lang.Override
  public boolean hasError() {
    return errorOrWarningAcceptanceCase_ == 1;
  }
  /**
   * <code>.com.ifit.glassos.IFitError error = 1;</code>
   */
  @java.lang.Override
  public com.ifit.glassos.util.IFitError getError() {
    if (errorOrWarningAcceptanceCase_ == 1) {
       return (com.ifit.glassos.util.IFitError) errorOrWarningAcceptance_;
    }
    return com.ifit.glassos.util.IFitError.getDefaultInstance();
  }
  /**
   * <code>.com.ifit.glassos.IFitError error = 1;</code>
   */
  private void setError(com.ifit.glassos.util.IFitError value) {
    value.getClass();
  errorOrWarningAcceptance_ = value;
    errorOrWarningAcceptanceCase_ = 1;
  }
  /**
   * <code>.com.ifit.glassos.IFitError error = 1;</code>
   */
  private void mergeError(com.ifit.glassos.util.IFitError value) {
    value.getClass();
  if (errorOrWarningAcceptanceCase_ == 1 &&
        errorOrWarningAcceptance_ != com.ifit.glassos.util.IFitError.getDefaultInstance()) {
      errorOrWarningAcceptance_ = com.ifit.glassos.util.IFitError.newBuilder((com.ifit.glassos.util.IFitError) errorOrWarningAcceptance_)
          .mergeFrom(value).buildPartial();
    } else {
      errorOrWarningAcceptance_ = value;
    }
    errorOrWarningAcceptanceCase_ = 1;
  }
  /**
   * <code>.com.ifit.glassos.IFitError error = 1;</code>
   */
  private void clearError() {
    if (errorOrWarningAcceptanceCase_ == 1) {
      errorOrWarningAcceptanceCase_ = 0;
      errorOrWarningAcceptance_ = null;
    }
  }

  public static final int WARNINGACCEPTANCETIME_FIELD_NUMBER = 2;
  /**
   * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
   */
  @java.lang.Override
  public boolean hasWarningAcceptanceTime() {
    return errorOrWarningAcceptanceCase_ == 2;
  }
  /**
   * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
   */
  @java.lang.Override
  public com.ifit.glassos.user.WarningAcceptance getWarningAcceptanceTime() {
    if (errorOrWarningAcceptanceCase_ == 2) {
       return (com.ifit.glassos.user.WarningAcceptance) errorOrWarningAcceptance_;
    }
    return com.ifit.glassos.user.WarningAcceptance.getDefaultInstance();
  }
  /**
   * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
   */
  private void setWarningAcceptanceTime(com.ifit.glassos.user.WarningAcceptance value) {
    value.getClass();
  errorOrWarningAcceptance_ = value;
    errorOrWarningAcceptanceCase_ = 2;
  }
  /**
   * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
   */
  private void mergeWarningAcceptanceTime(com.ifit.glassos.user.WarningAcceptance value) {
    value.getClass();
  if (errorOrWarningAcceptanceCase_ == 2 &&
        errorOrWarningAcceptance_ != com.ifit.glassos.user.WarningAcceptance.getDefaultInstance()) {
      errorOrWarningAcceptance_ = com.ifit.glassos.user.WarningAcceptance.newBuilder((com.ifit.glassos.user.WarningAcceptance) errorOrWarningAcceptance_)
          .mergeFrom(value).buildPartial();
    } else {
      errorOrWarningAcceptance_ = value;
    }
    errorOrWarningAcceptanceCase_ = 2;
  }
  /**
   * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
   */
  private void clearWarningAcceptanceTime() {
    if (errorOrWarningAcceptanceCase_ == 2) {
      errorOrWarningAcceptanceCase_ = 0;
      errorOrWarningAcceptance_ = null;
    }
  }

  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.user.WarningAcceptanceResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.user.WarningAcceptanceResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.user.WarningAcceptanceResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.user.WarningAcceptanceResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.WarningAcceptanceResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.user.WarningAcceptanceResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.WarningAcceptanceResult)
      com.ifit.glassos.user.WarningAcceptanceResultOrBuilder {
    // Construct using com.ifit.glassos.user.WarningAcceptanceResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ErrorOrWarningAcceptanceCase
        getErrorOrWarningAcceptanceCase() {
      return instance.getErrorOrWarningAcceptanceCase();
    }

    public Builder clearErrorOrWarningAcceptance() {
      copyOnWrite();
      instance.clearErrorOrWarningAcceptance();
      return this;
    }


    /**
     * <code>.com.ifit.glassos.IFitError error = 1;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return instance.hasError();
    }
    /**
     * <code>.com.ifit.glassos.IFitError error = 1;</code>
     */
    @java.lang.Override
    public com.ifit.glassos.util.IFitError getError() {
      return instance.getError();
    }
    /**
     * <code>.com.ifit.glassos.IFitError error = 1;</code>
     */
    public Builder setError(com.ifit.glassos.util.IFitError value) {
      copyOnWrite();
      instance.setError(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.IFitError error = 1;</code>
     */
    public Builder setError(
        com.ifit.glassos.util.IFitError.Builder builderForValue) {
      copyOnWrite();
      instance.setError(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.ifit.glassos.IFitError error = 1;</code>
     */
    public Builder mergeError(com.ifit.glassos.util.IFitError value) {
      copyOnWrite();
      instance.mergeError(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.IFitError error = 1;</code>
     */
    public Builder clearError() {
      copyOnWrite();
      instance.clearError();
      return this;
    }

    /**
     * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
     */
    @java.lang.Override
    public boolean hasWarningAcceptanceTime() {
      return instance.hasWarningAcceptanceTime();
    }
    /**
     * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
     */
    @java.lang.Override
    public com.ifit.glassos.user.WarningAcceptance getWarningAcceptanceTime() {
      return instance.getWarningAcceptanceTime();
    }
    /**
     * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
     */
    public Builder setWarningAcceptanceTime(com.ifit.glassos.user.WarningAcceptance value) {
      copyOnWrite();
      instance.setWarningAcceptanceTime(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
     */
    public Builder setWarningAcceptanceTime(
        com.ifit.glassos.user.WarningAcceptance.Builder builderForValue) {
      copyOnWrite();
      instance.setWarningAcceptanceTime(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
     */
    public Builder mergeWarningAcceptanceTime(com.ifit.glassos.user.WarningAcceptance value) {
      copyOnWrite();
      instance.mergeWarningAcceptanceTime(value);
      return this;
    }
    /**
     * <code>.com.ifit.glassos.WarningAcceptance warningAcceptanceTime = 2;</code>
     */
    public Builder clearWarningAcceptanceTime() {
      copyOnWrite();
      instance.clearWarningAcceptanceTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.WarningAcceptanceResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.user.WarningAcceptanceResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "errorOrWarningAcceptance_",
            "errorOrWarningAcceptanceCase_",
            com.ifit.glassos.util.IFitError.class,
            com.ifit.glassos.user.WarningAcceptance.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002<" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.user.WarningAcceptanceResult> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.user.WarningAcceptanceResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.user.WarningAcceptanceResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.WarningAcceptanceResult)
  private static final com.ifit.glassos.user.WarningAcceptanceResult DEFAULT_INSTANCE;
  static {
    WarningAcceptanceResult defaultInstance = new WarningAcceptanceResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      WarningAcceptanceResult.class, defaultInstance);
  }

  public static com.ifit.glassos.user.WarningAcceptanceResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<WarningAcceptanceResult> PARSER;

  public static com.google.protobuf.Parser<WarningAcceptanceResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

