// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/AuthService.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.auth;

/**
 * Protobuf type {@code com.ifit.glassos.AuthTokenList}
 */
public  final class AuthTokenList extends
    com.google.protobuf.GeneratedMessageLite<
        AuthTokenList, AuthTokenList.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.AuthTokenList)
    AuthTokenListOrBuilder {
  private AuthTokenList() {
    tokens_ = emptyProtobufList();
  }
  public static final int TOKENS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.ifit.glassos.auth.AuthToken> tokens_;
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ifit.glassos.auth.AuthToken> getTokensList() {
    return tokens_;
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  public java.util.List<? extends com.ifit.glassos.auth.AuthTokenOrBuilder> 
      getTokensOrBuilderList() {
    return tokens_;
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  @java.lang.Override
  public int getTokensCount() {
    return tokens_.size();
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  @java.lang.Override
  public com.ifit.glassos.auth.AuthToken getTokens(int index) {
    return tokens_.get(index);
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  public com.ifit.glassos.auth.AuthTokenOrBuilder getTokensOrBuilder(
      int index) {
    return tokens_.get(index);
  }
  private void ensureTokensIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.ifit.glassos.auth.AuthToken> tmp = tokens_;
    if (!tmp.isModifiable()) {
      tokens_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  private void setTokens(
      int index, com.ifit.glassos.auth.AuthToken value) {
    value.getClass();
  ensureTokensIsMutable();
    tokens_.set(index, value);
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  private void addTokens(com.ifit.glassos.auth.AuthToken value) {
    value.getClass();
  ensureTokensIsMutable();
    tokens_.add(value);
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  private void addTokens(
      int index, com.ifit.glassos.auth.AuthToken value) {
    value.getClass();
  ensureTokensIsMutable();
    tokens_.add(index, value);
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  private void addAllTokens(
      java.lang.Iterable<? extends com.ifit.glassos.auth.AuthToken> values) {
    ensureTokensIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, tokens_);
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  private void clearTokens() {
    tokens_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
   */
  private void removeTokens(int index) {
    ensureTokensIsMutable();
    tokens_.remove(index);
  }

  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.auth.AuthTokenList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.auth.AuthTokenList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.auth.AuthTokenList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.auth.AuthTokenList prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.AuthTokenList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.auth.AuthTokenList, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.AuthTokenList)
      com.ifit.glassos.auth.AuthTokenListOrBuilder {
    // Construct using com.ifit.glassos.auth.AuthTokenList.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.ifit.glassos.auth.AuthToken> getTokensList() {
      return java.util.Collections.unmodifiableList(
          instance.getTokensList());
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    @java.lang.Override
    public int getTokensCount() {
      return instance.getTokensCount();
    }/**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    @java.lang.Override
    public com.ifit.glassos.auth.AuthToken getTokens(int index) {
      return instance.getTokens(index);
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder setTokens(
        int index, com.ifit.glassos.auth.AuthToken value) {
      copyOnWrite();
      instance.setTokens(index, value);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder setTokens(
        int index, com.ifit.glassos.auth.AuthToken.Builder builderForValue) {
      copyOnWrite();
      instance.setTokens(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder addTokens(com.ifit.glassos.auth.AuthToken value) {
      copyOnWrite();
      instance.addTokens(value);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder addTokens(
        int index, com.ifit.glassos.auth.AuthToken value) {
      copyOnWrite();
      instance.addTokens(index, value);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder addTokens(
        com.ifit.glassos.auth.AuthToken.Builder builderForValue) {
      copyOnWrite();
      instance.addTokens(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder addTokens(
        int index, com.ifit.glassos.auth.AuthToken.Builder builderForValue) {
      copyOnWrite();
      instance.addTokens(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder addAllTokens(
        java.lang.Iterable<? extends com.ifit.glassos.auth.AuthToken> values) {
      copyOnWrite();
      instance.addAllTokens(values);
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder clearTokens() {
      copyOnWrite();
      instance.clearTokens();
      return this;
    }
    /**
     * <code>repeated .com.ifit.glassos.AuthToken tokens = 1;</code>
     */
    public Builder removeTokens(int index) {
      copyOnWrite();
      instance.removeTokens(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.AuthTokenList)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.auth.AuthTokenList();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "tokens_",
            com.ifit.glassos.auth.AuthToken.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.auth.AuthTokenList> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.auth.AuthTokenList.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.auth.AuthTokenList>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.AuthTokenList)
  private static final com.ifit.glassos.auth.AuthTokenList DEFAULT_INSTANCE;
  static {
    AuthTokenList defaultInstance = new AuthTokenList();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AuthTokenList.class, defaultInstance);
  }

  public static com.ifit.glassos.auth.AuthTokenList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuthTokenList> PARSER;

  public static com.google.protobuf.Parser<AuthTokenList> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

