// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util/Util.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.util;

/**
 * Protobuf type {@code com.ifit.glassos.WorkoutID}
 */
public  final class WorkoutID extends
    com.google.protobuf.GeneratedMessageLite<
        WorkoutID, WorkoutID.Builder> implements
    // @@protoc_insertion_point(message_implements:com.ifit.glassos.WorkoutID)
    WorkoutIDOrBuilder {
  private WorkoutID() {
    workoutID_ = "";
  }
  public static final int WORKOUTID_FIELD_NUMBER = 1;
  private java.lang.String workoutID_;
  /**
   * <code>string workoutID = 1;</code>
   * @return The workoutID.
   */
  @java.lang.Override
  public java.lang.String getWorkoutID() {
    return workoutID_;
  }
  /**
   * <code>string workoutID = 1;</code>
   * @return The bytes for workoutID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkoutIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(workoutID_);
  }
  /**
   * <code>string workoutID = 1;</code>
   * @param value The workoutID to set.
   */
  private void setWorkoutID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    workoutID_ = value;
  }
  /**
   * <code>string workoutID = 1;</code>
   */
  private void clearWorkoutID() {

    workoutID_ = getDefaultInstance().getWorkoutID();
  }
  /**
   * <code>string workoutID = 1;</code>
   * @param value The bytes for workoutID to set.
   */
  private void setWorkoutIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    workoutID_ = value.toStringUtf8();

  }

  public static com.ifit.glassos.util.WorkoutID parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.ifit.glassos.util.WorkoutID parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.ifit.glassos.util.WorkoutID parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.ifit.glassos.util.WorkoutID parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.ifit.glassos.util.WorkoutID prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.ifit.glassos.WorkoutID}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.ifit.glassos.util.WorkoutID, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ifit.glassos.WorkoutID)
      com.ifit.glassos.util.WorkoutIDOrBuilder {
    // Construct using com.ifit.glassos.util.WorkoutID.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string workoutID = 1;</code>
     * @return The workoutID.
     */
    @java.lang.Override
    public java.lang.String getWorkoutID() {
      return instance.getWorkoutID();
    }
    /**
     * <code>string workoutID = 1;</code>
     * @return The bytes for workoutID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkoutIDBytes() {
      return instance.getWorkoutIDBytes();
    }
    /**
     * <code>string workoutID = 1;</code>
     * @param value The workoutID to set.
     * @return This builder for chaining.
     */
    public Builder setWorkoutID(
        java.lang.String value) {
      copyOnWrite();
      instance.setWorkoutID(value);
      return this;
    }
    /**
     * <code>string workoutID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkoutID() {
      copyOnWrite();
      instance.clearWorkoutID();
      return this;
    }
    /**
     * <code>string workoutID = 1;</code>
     * @param value The bytes for workoutID to set.
     * @return This builder for chaining.
     */
    public Builder setWorkoutIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setWorkoutIDBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.ifit.glassos.WorkoutID)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.ifit.glassos.util.WorkoutID();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "workoutID_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.ifit.glassos.util.WorkoutID> parser = PARSER;
        if (parser == null) {
          synchronized (com.ifit.glassos.util.WorkoutID.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.ifit.glassos.util.WorkoutID>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.ifit.glassos.WorkoutID)
  private static final com.ifit.glassos.util.WorkoutID DEFAULT_INSTANCE;
  static {
    WorkoutID defaultInstance = new WorkoutID();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      WorkoutID.class, defaultInstance);
  }

  public static com.ifit.glassos.util.WorkoutID getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<WorkoutID> PARSER;

  public static com.google.protobuf.Parser<WorkoutID> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

