// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activitylog/ActivityLog.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.activitylog;

public interface ActivityLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.ActivityLog)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.ifit.glassos.ActivityLogMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.com.ifit.glassos.ActivityLogMetadata metadata = 1;</code>
   * @return The metadata.
   */
  com.ifit.glassos.activitylog.ActivityLogMetadata getMetadata();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 softwareNumber = 3;</code>
   * @return The softwareNumber.
   */
  int getSoftwareNumber();

  /**
   * <code>int64 startMsSinceEpoch = 4;</code>
   * @return The startMsSinceEpoch.
   */
  long getStartMsSinceEpoch();

  /**
   * <code>int64 endMsSinceEpoch = 5;</code>
   * @return The endMsSinceEpoch.
   */
  long getEndMsSinceEpoch();

  /**
   * <code>int32 durationMs = 6;</code>
   * @return The durationMs.
   */
  int getDurationMs();

  /**
   * <code>.com.ifit.glassos.ActivityLogStats stats = 7;</code>
   * @return Whether the stats field is set.
   */
  boolean hasStats();
  /**
   * <code>.com.ifit.glassos.ActivityLogStats stats = 7;</code>
   * @return The stats.
   */
  com.ifit.glassos.activitylog.ActivityLogStats getStats();

  /**
   * <code>.com.ifit.glassos.ActivityLogSummary summary = 8;</code>
   * @return Whether the summary field is set.
   */
  boolean hasSummary();
  /**
   * <code>.com.ifit.glassos.ActivityLogSummary summary = 8;</code>
   * @return The summary.
   */
  com.ifit.glassos.activitylog.ActivityLogSummary getSummary();
}
