#include <QSettings>
#include <QDebug>

#include "qzsettings.h"

namespace QZSettings
{

const uint32_t allSettingsCount = 366;
QVariant allSettings[allSettingsCount][2] =  {
    { cryptoKeySettingsProfiles, default_cryptoKeySettingsProfiles },
    { bluetooth_no_reconnection, default_bluetooth_no_reconnection },
    { bike_wheel_revs, default_bike_wheel_revs },
    { bluetooth_lastdevice_name, default_bluetooth_lastdevice_name },
    { bluetooth_lastdevice_address, default_bluetooth_lastdevice_address },
    { hrm_lastdevice_name, default_hrm_lastdevice_name },
    { hrm_lastdevice_address, default_hrm_lastdevice_address },
    { ftms_accessory_address, default_ftms_accessory_address },
    { ftms_accessory_lastdevice_name, default_ftms_accessory_lastdevice_name },
    { csc_sensor_address, default_csc_sensor_address },
    { csc_sensor_lastdevice_name, default_csc_sensor_lastdevice_name },
    { power_sensor_lastdevice_name, default_power_sensor_lastdevice_name },
    { power_sensor_address, default_power_sensor_address },
    { elite_rizer_lastdevice_name, default_elite_rizer_lastdevice_name },
    { elite_rizer_address, default_elite_rizer_address },
    { elite_sterzo_smart_lastdevice_name, default_elite_sterzo_smart_lastdevice_name },
    { elite_sterzo_smart_address, default_elite_sterzo_smart_address },
    { strava_accesstoken, default_strava_accesstoken },
    { strava_refreshtoken, default_strava_refreshtoken },
    { strava_lastrefresh, default_strava_lastrefresh },
    { strava_expires, default_strava_expires },
    { ui_zoom, default_ui_zoom },
    { bike_heartrate_service, default_bike_heartrate_service },
    { bike_resistance_offset, default_bike_resistance_offset },
    { bike_resistance_gain_f, default_bike_resistance_gain_f },
    { zwift_erg, default_zwift_erg },
    { zwift_erg_filter, default_zwift_erg_filter },
    { zwift_erg_filter_down, default_zwift_erg_filter_down },
    { zwift_negative_inclination_x2, default_zwift_negative_inclination_x2 },
    { zwift_inclination_offset, default_zwift_inclination_offset },
    { zwift_inclination_gain, default_zwift_inclination_gain },
    { echelon_resistance_offset, default_echelon_resistance_offset },
    { echelon_resistance_gain, default_echelon_resistance_gain },
    { speed_power_based, default_speed_power_based },
    { bike_resistance_start, default_bike_resistance_start },
    { age, default_age },
    { weight, default_weight },
    { ftp, default_ftp },
    { user_email, default_user_email },
    { user_nickname, default_user_nickname },
    { miles_unit, default_miles_unit },
    { pause_on_start, default_pause_on_start },
    { treadmill_force_speed, default_treadmill_force_speed },
    { pause_on_start_treadmill, default_pause_on_start_treadmill },
    { continuous_moving, default_continuous_moving },
    { bike_cadence_sensor, default_bike_cadence_sensor },
    { run_cadence_sensor, default_run_cadence_sensor },
    { bike_power_sensor, default_bike_power_sensor },
    { heart_rate_belt_name, default_heart_rate_belt_name },
    { heart_ignore_builtin, default_heart_ignore_builtin },
    { kcal_ignore_builtin, default_kcal_ignore_builtin },
    { ant_cadence, default_ant_cadence },
    { ant_heart, default_ant_heart },
    { ant_garmin, default_ant_garmin },
    { top_bar_enabled, default_top_bar_enabled },
    { peloton_username, default_peloton_username },
    { peloton_password, default_peloton_password },
    { peloton_difficulty, default_peloton_difficulty },
    { peloton_cadence_metric, default_peloton_cadence_metric },
    { peloton_heartrate_metric, default_peloton_heartrate_metric },
    { peloton_date, default_peloton_date },
    { peloton_description_link, default_peloton_description_link },
    { pzp_username, default_pzp_username },
    { pzp_password, default_pzp_password },
    { tile_speed_enabled, default_tile_speed_enabled },
    { tile_speed_order, default_tile_speed_order },
    { tile_inclination_enabled, default_tile_inclination_enabled },
    { tile_inclination_order, default_tile_inclination_order },
    { tile_cadence_enabled, default_tile_cadence_enabled },
    { tile_cadence_order, default_tile_cadence_order },
    { tile_elevation_enabled, default_tile_elevation_enabled },
    { tile_elevation_order, default_tile_elevation_order },
    { tile_calories_enabled, default_tile_calories_enabled },
    { tile_calories_order, default_tile_calories_order },
    { tile_odometer_enabled, default_tile_odometer_enabled },
    { tile_odometer_order, default_tile_odometer_order },
    { tile_pace_enabled, default_tile_pace_enabled },
    { tile_pace_order, default_tile_pace_order },
    { tile_resistance_enabled, default_tile_resistance_enabled },
    { tile_resistance_order, default_tile_resistance_order },
    { tile_watt_enabled, default_tile_watt_enabled },
    { tile_watt_order, default_tile_watt_order },
    { tile_weight_loss_enabled, default_tile_weight_loss_enabled },
    { tile_weight_loss_order, default_tile_weight_loss_order },
    { tile_avgwatt_enabled, default_tile_avgwatt_enabled },
    { tile_avgwatt_order, default_tile_avgwatt_order },
    { tile_ftp_enabled, default_tile_ftp_enabled },
    { tile_ftp_order, default_tile_ftp_order },
    { tile_heart_enabled, default_tile_heart_enabled },
    { tile_heart_order, default_tile_heart_order },
    { tile_fan_enabled, default_tile_fan_enabled },
    { tile_fan_order, default_tile_fan_order },
    { tile_jouls_enabled, default_tile_jouls_enabled },
    { tile_jouls_order, default_tile_jouls_order },
    { tile_elapsed_enabled, default_tile_elapsed_enabled },
    { tile_elapsed_order, default_tile_elapsed_order },
    { tile_lapelapsed_enabled, default_tile_lapelapsed_enabled },
    { tile_lapelapsed_order, default_tile_lapelapsed_order },
    { tile_moving_time_enabled, default_tile_moving_time_enabled },
    { tile_moving_time_order, default_tile_moving_time_order },
    { tile_peloton_offset_enabled, default_tile_peloton_offset_enabled },
    { tile_peloton_offset_order, default_tile_peloton_offset_order },
    { tile_peloton_difficulty_enabled, default_tile_peloton_difficulty_enabled },
    { tile_peloton_difficulty_order, default_tile_peloton_difficulty_order },
    { tile_peloton_resistance_enabled, default_tile_peloton_resistance_enabled },
    { tile_peloton_resistance_order, default_tile_peloton_resistance_order },
    { tile_datetime_enabled, default_tile_datetime_enabled },
    { tile_datetime_order, default_tile_datetime_order },
    { tile_target_resistance_enabled, default_tile_target_resistance_enabled },
    { tile_target_resistance_order, default_tile_target_resistance_order },
    { tile_target_peloton_resistance_enabled, default_tile_target_peloton_resistance_enabled },
    { tile_target_peloton_resistance_order, default_tile_target_peloton_resistance_order },
    { tile_target_cadence_enabled, default_tile_target_cadence_enabled },
    { tile_target_cadence_order, default_tile_target_cadence_order },
    { tile_target_power_enabled, default_tile_target_power_enabled },
    { tile_target_power_order, default_tile_target_power_order },
    { tile_target_zone_enabled, default_tile_target_zone_enabled },
    { tile_target_zone_order, default_tile_target_zone_order },
    { tile_target_speed_enabled, default_tile_target_speed_enabled },
    { tile_target_speed_order, default_tile_target_speed_order },
    { tile_target_incline_enabled, default_tile_target_incline_enabled },
    { tile_target_incline_order, default_tile_target_incline_order },
    { tile_strokes_count_enabled, default_tile_strokes_count_enabled },
    { tile_strokes_count_order, default_tile_strokes_count_order },
    { tile_strokes_length_enabled, default_tile_strokes_length_enabled },
    { tile_strokes_length_order, default_tile_strokes_length_order },
    { tile_watt_kg_enabled, default_tile_watt_kg_enabled },
    { tile_watt_kg_order, default_tile_watt_kg_order },
    { tile_gears_enabled, default_tile_gears_enabled },
    { tile_gears_order, default_tile_gears_order },
    { tile_remainingtimetrainprogramrow_enabled, default_tile_remainingtimetrainprogramrow_enabled },
    { tile_remainingtimetrainprogramrow_order, default_tile_remainingtimetrainprogramrow_order },
    { tile_nextrowstrainprogram_enabled, default_tile_nextrowstrainprogram_enabled },
    { tile_nextrowstrainprogram_order, default_tile_nextrowstrainprogram_order },
    { tile_mets_enabled, default_tile_mets_enabled },
    { tile_mets_order, default_tile_mets_order },
    { tile_targetmets_enabled, default_tile_targetmets_enabled },
    { tile_targetmets_order, default_tile_targetmets_order },
    { tile_steering_angle_enabled, default_tile_steering_angle_enabled },
    { tile_steering_angle_order, default_tile_steering_angle_order },
    { tile_pid_hr_enabled, default_tile_pid_hr_enabled },
    { tile_pid_hr_order, default_tile_pid_hr_order },
    { heart_rate_zone1, default_heart_rate_zone1 },
    { heart_rate_zone2, default_heart_rate_zone2 },
    { heart_rate_zone3, default_heart_rate_zone3 },
    { heart_rate_zone4, default_heart_rate_zone4 },
    { heart_max_override_enable, default_heart_max_override_enable },
    { heart_max_override_value, default_heart_max_override_value },
    { peloton_gain, default_peloton_gain },
    { peloton_offset, default_peloton_offset },
    { treadmill_pid_heart_zone, default_treadmill_pid_heart_zone },
    { pacef_1mile, default_pacef_1mile },
    { pacef_5km, default_pacef_5km },
    { pacef_10km, default_pacef_10km },
    { pacef_halfmarathon, default_pacef_halfmarathon },
    { pacef_marathon, default_pacef_marathon },
    { pace_default, default_pace_default },
    { domyos_treadmill_buttons, default_domyos_treadmill_buttons },
    { domyos_treadmill_distance_display, default_domyos_treadmill_distance_display },
    { domyos_treadmill_display_invert, default_domyos_treadmill_display_invert },
    { domyos_bike_cadence_filter, default_domyos_bike_cadence_filter },
    { domyos_bike_display_calories, default_domyos_bike_display_calories },
    { domyos_elliptical_speed_ratio, default_domyos_elliptical_speed_ratio },
    { eslinker_cadenza, default_eslinker_cadenza },
    { echelon_watttable, default_echelon_watttable },
    { proform_wheel_ratio, default_proform_wheel_ratio },
    { proform_tour_de_france_clc, default_proform_tour_de_france_clc },
    { proform_tdf_jonseed_watt, default_proform_tdf_jonseed_watt },
    { proform_studio, default_proform_studio },
    { proform_tdf_10, default_proform_tdf_10 },
    { horizon_gr7_cadence_multiplier, default_horizon_gr7_cadence_multiplier },
    { fitshow_user_id, default_fitshow_user_id },
    { inspire_peloton_formula, default_inspire_peloton_formula },
    { inspire_peloton_formula2, default_inspire_peloton_formula2 },
    { hammer_racer_s, default_hammer_racer_s },
    { pafers_treadmill, default_pafers_treadmill },
    { yesoul_peloton_formula, default_yesoul_peloton_formula },
    { nordictrack_10_treadmill, default_nordictrack_10_treadmill },
    { nordictrack_t65s_treadmill, default_nordictrack_t65s_treadmill },
    { toorx_3_0, default_toorx_3_0 },
    { toorx_65s_evo, default_toorx_65s_evo },
    { jtx_fitness_sprint_treadmill, default_jtx_fitness_sprint_treadmill },
    { dkn_endurun_treadmill, default_dkn_endurun_treadmill },
    { trx_route_key, default_trx_route_key },
    { bh_spada_2, default_bh_spada_2 },
    { toorx_bike, default_toorx_bike },
    { toorx_ftms, default_toorx_ftms },
    { jll_IC400_bike, default_jll_IC400_bike },
    { fytter_ri08_bike, default_fytter_ri08_bike },
    { asviva_bike, default_asviva_bike },
    { hertz_xr_770, default_hertz_xr_770 },
    { m3i_bike_id, default_m3i_bike_id },
    { m3i_bike_speed_buffsize, default_m3i_bike_speed_buffsize },
    { m3i_bike_qt_search, default_m3i_bike_qt_search },
    { m3i_bike_kcal, default_m3i_bike_kcal },
    { snode_bike, default_snode_bike },
    { fitplus_bike, default_fitplus_bike },
    { virtufit_etappe, default_virtufit_etappe },
    { flywheel_filter, default_flywheel_filter },
    { flywheel_life_fitness_ic8, default_flywheel_life_fitness_ic8 },
    { sole_treadmill_inclination, default_sole_treadmill_inclination },
    { sole_treadmill_miles, default_sole_treadmill_miles },
    { sole_treadmill_f65, default_sole_treadmill_f65 },
    { sole_treadmill_f63, default_sole_treadmill_f63 },
    { sole_treadmill_tt8, default_sole_treadmill_tt8 },
    { schwinn_bike_resistance, default_schwinn_bike_resistance },
    { schwinn_bike_resistance_v2, default_schwinn_bike_resistance_v2 },
    { technogym_myrun_treadmill_experimental, default_technogym_myrun_treadmill_experimental },
    { trainprogram_random, default_trainprogram_random },
    { trainprogram_total, default_trainprogram_total },
    { trainprogram_period_seconds, default_trainprogram_period_seconds },
    { trainprogram_speed_min, default_trainprogram_speed_min },
    { trainprogram_speed_max, default_trainprogram_speed_max },
    { trainprogram_incline_min, default_trainprogram_incline_min },
    { trainprogram_incline_max, default_trainprogram_incline_max },
    { trainprogram_resistance_min, default_trainprogram_resistance_min },
    { trainprogram_resistance_max, default_trainprogram_resistance_max },
    { watt_offset, default_watt_offset },
    { watt_gain, default_watt_gain },
    { power_avg_5s, default_power_avg_5s },
    { instant_power_on_pause, default_instant_power_on_pause },
    { speed_offset, default_speed_offset },
    { speed_gain, default_speed_gain },
    { filter_device, default_filter_device },
    { strava_suffix, default_strava_suffix },
    { cadence_sensor_name, default_cadence_sensor_name },
    { cadence_sensor_as_bike, default_cadence_sensor_as_bike },
    { cadence_sensor_speed_ratio, default_cadence_sensor_speed_ratio },
    { power_hr_pwr1, default_power_hr_pwr1 },
    { power_hr_hr1, default_power_hr_hr1 },
    { power_hr_pwr2, default_power_hr_pwr2 },
    { power_hr_hr2, default_power_hr_hr2 },
    { power_sensor_name, default_power_sensor_name },
    { power_sensor_as_bike, default_power_sensor_as_bike },
    { power_sensor_as_treadmill, default_power_sensor_as_treadmill },
    { powr_sensor_running_cadence_double, default_powr_sensor_running_cadence_double },
    { elite_rizer_name, default_elite_rizer_name },
    { elite_sterzo_smart_name, default_elite_sterzo_smart_name },
    { ftms_accessory_name, default_ftms_accessory_name },
    { ss2k_shift_step, default_ss2k_shift_step },
    { fitmetria_fanfit_enable, default_fitmetria_fanfit_enable },
    { fitmetria_fanfit_mode, default_fitmetria_fanfit_mode },
    { fitmetria_fanfit_min, default_fitmetria_fanfit_min },
    { fitmetria_fanfit_max, default_fitmetria_fanfit_max },
    { virtualbike_forceresistance, default_virtualbike_forceresistance },
    { bluetooth_relaxed, default_bluetooth_relaxed },
    { bluetooth_30m_hangs, default_bluetooth_30m_hangs },
    { battery_service, default_battery_service },
    { service_changed, default_service_changed },
    { virtual_device_enabled, default_virtual_device_enabled },
    { virtual_device_bluetooth, default_virtual_device_bluetooth },
    { ios_peloton_workaround, default_ios_peloton_workaround },
    { android_wakelock, default_android_wakelock },
    { log_debug, default_log_debug },
    { virtual_device_onlyheart, default_virtual_device_onlyheart },
    { virtual_device_echelon, default_virtual_device_echelon },
    { virtual_device_ifit, default_virtual_device_ifit },
    { virtual_device_rower, default_virtual_device_rower },
    { virtual_device_force_bike, default_virtual_device_force_bike },
    { volume_change_gears, default_volume_change_gears },
    { applewatch_fakedevice, default_applewatch_fakedevice },
    { zwift_erg_resistance_down, default_zwift_erg_resistance_down },
    { zwift_erg_resistance_up, default_zwift_erg_resistance_up },
    { horizon_paragon_x, default_horizon_paragon_x },
    { treadmill_step_speed, default_treadmill_step_speed },
    { treadmill_step_incline, default_treadmill_step_incline },
    { fitshow_anyrun, default_fitshow_anyrun },
    { nordictrack_s30_treadmill, default_nordictrack_s30_treadmill },
    { renpho_peloton_conversion_v2, default_renpho_peloton_conversion_v2 },
    { ss2k_resistance_sample_1, default_ss2k_resistance_sample_1 },
    { ss2k_shift_step_sample_1, default_ss2k_shift_step_sample_1 },
    { ss2k_resistance_sample_2, default_ss2k_resistance_sample_2 },
    { ss2k_shift_step_sample_2, default_ss2k_shift_step_sample_2 },
    { ss2k_resistance_sample_3, default_ss2k_resistance_sample_3 },
    { ss2k_shift_step_sample_3, default_ss2k_shift_step_sample_3 },
    { ss2k_resistance_sample_4, default_ss2k_resistance_sample_4 },
    { ss2k_shift_step_sample_4, default_ss2k_shift_step_sample_4 },
    { fitshow_truetimer, default_fitshow_truetimer },
    { elite_rizer_gain, default_elite_rizer_gain },
    { tile_ext_incline_enabled, default_tile_ext_incline_enabled },
    { tile_ext_incline_order, default_tile_ext_incline_order },
    { reebok_fr30_treadmill, default_reebok_fr30_treadmill },
    { horizon_treadmill_7_8, default_horizon_treadmill_7_8 },
    { profile_name, default_profile_name },
    { tile_cadence_color_enabled, default_tile_cadence_color_enabled },
    { tile_peloton_remaining_enabled, default_tile_peloton_remaining_enabled },
    { tile_peloton_remaining_order, default_tile_peloton_remaining_order },
    { tile_peloton_resistance_color_enabled, default_tile_peloton_resistance_color_enabled },
    { dircon_yes, default_dircon_yes },
    { dircon_server_base_port, default_dircon_server_base_port },
    { ios_cache_heart_device, default_ios_cache_heart_device },
    { app_opening, default_app_opening },
    { proformtdf4ip, default_proformtdf4ip },
    { fitfiu_mc_v460, default_fitfiu_mc_v460 },
    { bike_weight, default_bike_weight },
    { kingsmith_encrypt_v2, default_kingsmith_encrypt_v2 },
    { proform_treadmill_9_0, default_proform_treadmill_9_0 },
    { proform_treadmill_1800i, default_proform_treadmill_1800i },
    { cadence_offset, default_cadence_offset },
    { cadence_gain, default_cadence_gain },
    { sp_ht_9600ie, default_sp_ht_9600ie },
    { tts_enabled, default_tts_enabled },
    { tts_summary_sec, default_tts_summary_sec },
    { tts_act_speed, default_tts_act_speed },
    { tts_avg_speed, default_tts_avg_speed },
    { tts_max_speed, default_tts_max_speed },
    { tts_act_inclination, default_tts_act_inclination },
    { tts_act_cadence, default_tts_act_cadence },
    { tts_avg_cadence, default_tts_avg_cadence },
    { tts_max_cadence, default_tts_max_cadence },
    { tts_act_elevation, default_tts_act_elevation },
    { tts_act_calories, default_tts_act_calories },
    { tts_act_odometer, default_tts_act_odometer },
    { tts_act_pace, default_tts_act_pace },
    { tts_avg_pace, default_tts_avg_pace },
    { tts_max_pace, default_tts_max_pace },
    { tts_act_resistance, default_tts_act_resistance },
    { tts_avg_resistance, default_tts_avg_resistance },
    { tts_max_resistance, default_tts_max_resistance },
    { tts_act_watt, default_tts_act_watt },
    { tts_avg_watt, default_tts_avg_watt },
    { tts_max_watt, default_tts_max_watt },
    { tts_act_ftp, default_tts_act_ftp },
    { tts_avg_ftp, default_tts_avg_ftp },
    { tts_max_ftp, default_tts_max_ftp },
    { tts_act_heart, default_tts_act_heart },
    { tts_avg_heart, default_tts_avg_heart },
    { tts_max_heart, default_tts_max_heart },
    { tts_act_jouls, default_tts_act_jouls },
    { tts_act_elapsed, default_tts_act_elapsed },
    { tts_act_peloton_resistance, default_tts_act_peloton_resistance },
    { tts_avg_peloton_resistance, default_tts_avg_peloton_resistance },
    { tts_max_peloton_resistance, default_tts_max_peloton_resistance },
    { tts_act_target_peloton_resistance, default_tts_act_target_peloton_resistance },
    { tts_act_target_cadence, default_tts_act_target_cadence },
    { tts_act_target_power, default_tts_act_target_power },
    { tts_act_target_zone, default_tts_act_target_zone },
    { tts_act_target_speed, default_tts_act_target_speed },
    { tts_act_target_incline, default_tts_act_target_incline },
    { tts_act_watt_kg, default_tts_act_watt_kg },
    { tts_avg_watt_kg, default_tts_avg_watt_kg },
    { tts_max_watt_kg, default_tts_max_watt_kg },
    { fakedevice_elliptical, default_fakedevice_elliptical },
    { nordictrack_2950_ip, default_nordictrack_2950_ip },
    { tile_instantaneous_stride_length_enabled, default_tile_instantaneous_stride_length_enabled },
    { tile_instantaneous_stride_length_order, default_tile_instantaneous_stride_length_order },
    { tile_ground_contact_enabled, default_tile_ground_contact_enabled },
    { tile_ground_contact_order, default_tile_ground_contact_order },
    { tile_vertical_oscillation_enabled, default_tile_vertical_oscillation_enabled },
    { tile_vertical_oscillation_order, default_tile_vertical_oscillation_order },
    { sex, default_sex },
    { maps_type, default_maps_type },
    { ss2k_max_resistance, default_ss2k_max_resistance },
    { ss2k_min_resistance, default_ss2k_min_resistance },
    { proform_treadmill_se, default_proform_treadmill_se },
    { proformtreadmillip, default_proformtreadmillip },
    { kingsmith_encrypt_v3, default_kingsmith_encrypt_v3 },
    { tdf_10_ip, default_tdf_10_ip },
    { fakedevice_treadmill, default_fakedevice_treadmill },
    { video_playback_window_s, default_video_playback_window_s },
    {horizon_treadmill_profile_user1, default_horizon_treadmill_profile_user1},
    {horizon_treadmill_profile_user2, default_horizon_treadmill_profile_user2},
    {horizon_treadmill_profile_user3, default_horizon_treadmill_profile_user3},
    {horizon_treadmill_profile_user4, default_horizon_treadmill_profile_user4},
    {horizon_treadmill_profile_user5, default_horizon_treadmill_profile_user5},
    {nordictrack_gx_2_7, default_nordictrack_gx_2_7}
};

void qDebugAllSettings(bool showDefaults) {
    QSettings settings;

    // make a copy of the settings for sorting
    std::vector<QVariant*> sorted;
    for(uint32_t i=0; i<allSettingsCount; i++) {
        sorted.push_back(allSettings[i]);
    }

    // sort the settings alphabetically
    struct { bool operator()(QVariant * a, QVariant * b) { return a[0].toString() < b[0].toString(); }} comparer;
    std::sort(sorted.begin(), sorted.end(), comparer);

    for(uint32_t i=0; i<sorted.size(); i++) {
        QVariant * item = sorted[i];
        QString key = item[0].toString();
        QVariant defaultValue = item[1];

        if(!showDefaults) {
            qDebug() << key << settings.value(key, defaultValue);
        } else {
            qDebug() << "("
                     << key
                     <<", "
                     << defaultValue
                     << ") = "
                     << settings.value(key, defaultValue);
        }
    }

}
}
