// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: console/calibration/InclineCalibration.proto

// Protobuf Java Version: 3.25.3
package com.ifit.glassos.console.calibration;

public interface InclineCalibrationStateResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ifit.glassos.InclineCalibrationStateResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.ifit.glassos.CalibrateInclineState state = 1;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.com.ifit.glassos.CalibrateInclineState state = 1;</code>
   * @return The state.
   */
  com.ifit.glassos.console.calibration.CalibrateInclineState getState();
}
